###############################################################################
# (c) 2024 W. Spann Systems Consulting
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

"""
Provides a non-interactive zero-knowledge (NIZK) proof of knowledge (PoK) of N _equal_ discrete logarithms, over a
prime-order elliptic curve group (e.g., NIST P-256).
- This NIZK proof construction is based on the `Chaum-Pedersen (interactive) protocol
<https://link.springer.com/content/pdf/10.1007/3-540-48071-4_7.pdf>` for proving knowledge in ZK of _two_ equal discrete
logarithms, which has been adapted to operate over elliptic curves and generalized from 2 to N equal discrete logs.
- The `Fiat-Shamir transform <https://en.wikipedia.org/wiki/Fiat%E2%80%93Shamir_heuristic>` is then used to produce a
non-interactive ZK proof construction, featuring both non-interactive proof generation & verification.
"""
from __future__ import annotations

import base64
import binascii
import hashlib

from typing import NewType, Tuple

from Cryptodome.PublicKey import ECC
from Cryptodome.Util import number

from scriptless_zkp import STRING_ENCODING_FIELD_DELIMITER
from scriptless_zkp.ecc.ecc_utils import generate_random_nonce
from scriptless_zkp.ecc.weierstrass_curves import WeierstrassEllipticCurveConfig

from scriptless_zkp.hashing import PrimeBasedTruncatedHasher


NIZKEqualDiscreteLogsProofSignature = NewType('NIZKEqualDiscreteLogsProofSignature', int)
"""
Efficient type for the NIZK proof's signature, which auto-casts to an `int`, but not from an `int`, providing type
safety in function & method calls (i.e., where other int-typed parameters may be present).
"""

NIZKEqualDiscreteLogsProofHash = NewType('NIZKEqualDiscreteLogsProofHash', int)
"""
Efficient type for the NIZK proof's public hash, which auto-casts to an `int`, but not from an `int, providing type
safety in function & method calls (i.e., where other int-typed parameters may be present).
"""

ECCDiscreteLogBaseAndProduct = NewType('ECCDiscreteLogBaseAndProduct', Tuple[ECC.EccPoint, ECC.EccPoint])
"""
Efficient type for an ECC base point/reference (product) point pair (i.e., where `ref_point := dlog * base_point`),
such that knowledge of the discrete logarithm (witness) being proven is the discrete log of the reference point with
respect to this base point.
"""


class NIZKEqualDiscreteLogsContext:
    DEFAULT_HASH_ALGORITHM: str = hashlib.sha3_256().name  # Note: Suitable for 255 & 256-bit elliptic curves.
    DEFAULT_DOMAIN_SEPARATION_TAG = 'nizk_equal_dlogs_proof'

    curve_config: WeierstrassEllipticCurveConfig
    domain_separator: str

    def __init__(
            self,
            curve_config: WeierstrassEllipticCurveConfig,
            domain_separation_tag: str = DEFAULT_DOMAIN_SEPARATION_TAG
    ):
        """
        Initializes an NIZK Proof of Knowledge (PoK) of Equal Discrete Logs Context, which encapsulates common
        configuration parameters to be used for proof construction & verification, in addition to providing several
        methods used by both the prover & the proof's verifier.
        :param curve_config: elliptic curve configuration to be used.
        :param domain_separation_tag: domain separation tag to be used for ensuring distinct hashes from other uses of
               the configured cryptographic hash algorithm.
        """
        self.curve_config = curve_config
        self.domain_separator = domain_separation_tag

    @property
    def curve(self) -> str:
        """Returns the (primary) name of the configured elliptic curve."""
        return self.curve_config.curve

    @property
    def order(self) -> int:
        """
        Returns the configured elliptic curve sub-group's order (i.e., the order of the sub-group generated by `G`).
        """
        return self.curve_config.order

    # noinspection PyPep8Naming
    @property
    def G(self) -> ECC.EccPoint:
        """Returns the configured elliptic curve's generator (base) point."""
        return self.curve_config.base_point

    def calc_public_hash(
            self,
            discrete_log_params_set: NIZKDiscreteLogParameterSet,
            secret_nonce_points: list[ECC.EccPoint],
            hash_algorithm: str
    ) -> NIZKEqualDiscreteLogsProofHash:
        # Verify we have the required nonce point per dlog base/ref. point pair.
        assert len(secret_nonce_points) == len(discrete_log_params_set.dlog_base_and_ref_points)

        # Init. a truncated hasher for hashing to bit-length of elliptic curve sub-group's order (i.e., `|<G>|`), and
        # use a domain separation tag to ensure distinct hashes from other uses of SHA3-256.
        hasher = PrimeBasedTruncatedHasher(
            self.order,
            hash_algorithm=hash_algorithm,
            domain_separation_tag=self.domain_separator
        )

        # Hash each pair of discrete log base and reference points (where each `ref_point := dlog * dlog_base`), using
        # the 'SEC1' binary encoding for each EC point w/out point compression (in order to retain each EC point's
        # y-coordinate's entropy).
        for dlog_base, dlog_ref_point in discrete_log_params_set.dlog_base_and_ref_points:
            hasher.update(self.encode_ecc_point(dlog_base))
            hasher.update(self.encode_ecc_point(dlog_ref_point))

        # Hash each nonce point, following 'SEC1' encoding w/out EC point compression.
        # (Note: There is one nonce point per dlog base/ref point pair.)
        for nonce_point in secret_nonce_points:
            hasher.update(self.encode_ecc_point(nonce_point))

        # Finalize the (possibly) bit-length truncated hash and encode as a big integer.
        pub_hash: int = hasher.intdigest()

        return NIZKEqualDiscreteLogsProofHash(pub_hash)

    def generate_random_nonce(self) -> int:
        """
        Generates a random big integer in the range `[1, q-1]` inclusive, where `q` is the configured elliptic curve
        sub-group's order (i.e., `|<G>|` where `<G>` is the sub-group generated by the public base point `G`).
        :return: a random big integer in the range `[1, q-1]` inclusive, where `q` is the configured elliptic curve
                 sub-group's order.
        """
        return generate_random_nonce(self.curve_config)

    @staticmethod
    def encode_public_key(public_key: ECC.EccKey) -> bytes:
        if public_key.has_private():
            return public_key.public_key().export_key(format='SEC1')
        else:
            return public_key.export_key(format='SEC1')

    def ecc_point_to_pubkey(self, ecc_point: ECC.EccPoint) -> ECC.EccKey:
        if self.curve_config.is_point_on_curve(ecc_point):
            return ECC.construct(curve=self.curve_config.curve, point_x=ecc_point.x, point_y=ecc_point.y)
        else:
            raise ValueError(f"Provided ECC point is not on the configured elliptic curve: '{self.curve_config.curve}'")

    def encode_ecc_point(self, ecc_point: ECC.EccPoint, point_compression: bool = False) -> bytes:
        """
        Encodes the provided ECC point as a binary string, using the 'SEC1' format w/out point compression by default.
        """
        return self.ecc_point_to_pubkey(ecc_point).export_key(format='SEC1', compress=point_compression)

    def base64_encode_ecc_point(self, ecc_point: ECC.EccPoint, point_compression: bool = False) -> str:
        """
        Base64-encodes the provided ECC point, using the 'SEC1' binary format w/out point compression by default.
        """
        ecc_point_SEC1: bytes = self.encode_ecc_point(ecc_point, point_compression=point_compression)
        return base64.b64encode(ecc_point_SEC1).decode('utf-8')


class NIZKDiscreteLogParameterSet:
    # Minimum number of discrete log base/ref. point pairs.
    MIN_DISCRETE_LOGS: int = 1  # Note: This protocol generalizes to the single discrete case.
    # Minimum number of fields in a proof's encoded parameter-set.
    MIN_FIELDS_COUNT: int = 4

    curve_config: WeierstrassEllipticCurveConfig
    dlog_base_and_ref_points: list[ECCDiscreteLogBaseAndProduct]
    hash_algo: str

    def __init__(
            self,
            curve_config: WeierstrassEllipticCurveConfig,
            dlog_base_and_ref_points: list[ECCDiscreteLogBaseAndProduct],
            hash_algorithm: str = NIZKEqualDiscreteLogsContext.DEFAULT_HASH_ALGORITHM
    ):
        # Ensure the minimum number of dlog base/dlog ref. point pairs were provided.
        assert len(dlog_base_and_ref_points) >= NIZKDiscreteLogParameterSet.MIN_DISCRETE_LOGS

        self.curve_config = curve_config
        self.hash_algo = hash_algorithm
        self.dlog_base_and_ref_points = dlog_base_and_ref_points

    @classmethod
    def from_string_encoding(cls, encoded_parameter_set: str) -> NIZKDiscreteLogParameterSet:
        """
        Decodes a set of elliptic curve discrete log product/base point pairs (a component of an NIZK equal discrete
        logs proof) from a colon-delimited string of `key=value` formatted properties & base64-encoded binary values,
        as follows:
            `curve=<ECC-curve-name>:dlogs-count=<dlogs-count>:<dlog-base-1>:<ref-pt-1>[:<dlog-base-i>:<ref-pt-i>]...`
        :param encoded_parameter_set: a string encoding of a set of elliptic curve discrete log product/base point
               pairs, which uses base64-encoding for binary values.
        :return: a set of elliptic curve discrete log product/base point pairs, if this encoded parameter-set is valid.
        :raises ValueError: if the provided encoded set of discrete log product/base point pairs is improperly encoded
                or incomplete.
        """
        parsed_fields: list[str] = encoded_parameter_set.split(STRING_ENCODING_FIELD_DELIMITER)
        if len(parsed_fields) < cls.MIN_FIELDS_COUNT:
            raise ValueError(
                f"Invalid parameter-set of discrete log product/base point pairs for NIZK equal discrete logs proof"
                f" -- expected at least 3 fields, but found [{len(parsed_fields)}]."
            )

        # Extract the curve name from the encoded proof.
        curve_name_field: str = parsed_fields[0]
        _, curve_name = curve_name_field.split('=')

        curve_config: WeierstrassEllipticCurveConfig | None = WeierstrassEllipticCurveConfig.for_curve_name(curve_name)
        if curve_config is None:
            raise ValueError(
                f"Invalid NIZK equal discrete logs proof encoding -- unsupported elliptic curve with name:"
                f" '{curve_name}' specified for parameter-set of discrete log product/base point pairs."
            )

        # Extract the number of discrete logs being proven equal.
        _, dlogs_count_str = parsed_fields[1].split('=')
        dlogs_count = int(dlogs_count_str)

        # Validate we have the expected number of discrete log product/base point pairs.
        if dlogs_count < NIZKDiscreteLogParameterSet.MIN_DISCRETE_LOGS:
            raise ValueError(
                f"Invalid NIZK equal discrete logs proof parameter-set encoding -- expected at least"
                f" {NIZKDiscreteLogParameterSet.MIN_DISCRETE_LOGS} discrete log product/base point pairs, but found"
                f" [{dlogs_count}]."
            )
        elif len(parsed_fields) - 2 < dlogs_count or (len(parsed_fields) - 2) % 2 != 0:
            raise ValueError(
                f"Invalid NIZK equal discrete logs proof parameter-set encoding -- expected [{dlogs_count}] discrete"
                f" log product/base point pairs, but found [{(len(parsed_fields) - 2) // 2}]."
            )

        # Extract the encoded discrete log parameters.
        dlog_base_and_ref_points: list[ECCDiscreteLogBaseAndProduct] = []
        for i in range(2, len(parsed_fields), 2):
            dlog_base_field: str = parsed_fields[i]
            ref_pt_field: str = parsed_fields[i + 1]

            try:
                dlog_base_bytes: bytes = base64.b64decode(dlog_base_field)
                ref_pt_bytes: bytes = base64.b64decode(ref_pt_field)

                dlog_base = ECC.import_key(dlog_base_bytes, curve_name=curve_name)
                ref_pt = ECC.import_key(ref_pt_bytes, curve_name=curve_name)
            except (ValueError, TypeError, binascii.Error) as ex:
                raise ValueError(
                    f"Invalid NIZK equal discrete logs proof encoding -- failed to decode the set of discrete log"
                    f" product/base point pairs, due to exception: {ex}"
                ) from ex
            else:
                dlog_base_and_ref_points.append(ECCDiscreteLogBaseAndProduct((dlog_base, ref_pt)))

        # TODO: Parse the hash algorithm used for the proof, since this should be specified in the parameter-set's
        #   constructor. (Note: This field is already present in the NIZK proof's encoding.)
        return NIZKDiscreteLogParameterSet(
            curve_config,
            dlog_base_and_ref_points
        )

    def encode_as_string(self) -> str:
        # noinspection PyCompatibility
        """
        Encodes this discrete logarithms parameter-set, including the configured elliptic curve's "primary" name, and
        the number of discrete log parameter (dlog base/reference point) pairs, as a colon-delimited string of
        `key=value` formatted properties & base64-encoded binary values, as follows:
            `curve=<ECC-curve-name>:dlogs-count=<dlogs-count>:<dlog-base-1>:<ref-pt-1>[:<dlog-base-i>:<ref-pt-i>]...`
        :return: a string encoding of this discrete logarithms parameter-set, which uses base64-encoding for binary
                 values.
        """
        context = NIZKEqualDiscreteLogsContext(self.curve_config, self.hash_algo)
        encoded_params: list[str] = []

        # Indicate the configured elliptic curve (by "primary" name).
        curve_name_field: str = f"curve={self.curve_config.curve}"
        encoded_params.append(curve_name_field)

        # Indicate how many discrete logs are being proven equal (i.e., to simplify decoding of the variable-length
        # parameter-set).
        dlogs_count_field: str = f"dlogs_count={len(self.dlog_base_and_ref_points)}"
        encoded_params.append(dlogs_count_field)

        for dlog_base, dlog_ref_point in self.dlog_base_and_ref_points:
            encoded_params.append(
                context.base64_encode_ecc_point(dlog_base)
            )
            encoded_params.append(
                context.base64_encode_ecc_point(dlog_ref_point)
            )

        return STRING_ENCODING_FIELD_DELIMITER.join(encoded_params)


class NIZKEqualDiscreteLogsProof:
    context: NIZKEqualDiscreteLogsContext
    discrete_log_params_set: NIZKDiscreteLogParameterSet
    proof_pub_hash: NIZKEqualDiscreteLogsProofHash
    proof_signature: NIZKEqualDiscreteLogsProofSignature
    hash_algo: str

    # Minimum number of fields in a proof's encoded parameter-set.
    MIN_FIELDS_COUNT: int = NIZKDiscreteLogParameterSet.MIN_FIELDS_COUNT + 3

    def __init__(
            self,
            discrete_log_params_set: NIZKDiscreteLogParameterSet,
            proof_public_hash: NIZKEqualDiscreteLogsProofHash,
            proof_signature: NIZKEqualDiscreteLogsProofSignature,
            hash_algorithm: str
    ):
        self.curve_config = discrete_log_params_set.curve_config
        self.hash_algo = hash_algorithm
        self.context = NIZKEqualDiscreteLogsContext(discrete_log_params_set.curve_config)
        self.discrete_log_params_set = discrete_log_params_set
        self.proof_pub_hash = proof_public_hash
        self.proof_signature = proof_signature

    @classmethod
    def from_string_encoding(cls, encoded_proof: str) -> NIZKEqualDiscreteLogsProof:
        # noinspection PyCompatibility
        """
        Decodes an NIZK proof of knowledge (PoK) of equal discrete logarithms from a colon-delimited string of key=value
        formatted properties & base64-encoded binary values, as follows:
            `hash-algo=<hash-algorithm>:<encoded_dlog_params>:<proof_pub_hash>:<proof_signature>`
        :param encoded_proof: a string encoding of an NIZK proof of knowledge (PoK) of equal discrete logarithms, which
               uses base64-encoding for binary values.
        :return: an NIZK proof of knowledge (PoK) of equal discrete logarithms, if the encoded proof is valid; otherwise,
                `None`.
        :raises ValueError: if provided encoded NIZK proof is improperly encoded or incomplete.
        """
        proof_fields: list[str] = encoded_proof.split(STRING_ENCODING_FIELD_DELIMITER)
        if len(proof_fields) < cls.MIN_FIELDS_COUNT:
            raise ValueError(
                f"Invalid NIZK equal discrete logs proof encoding -- expected at least [{cls.MIN_FIELDS_COUNT}] fields,"
                f" but found [{len(proof_fields)}]."
            )

        # Extract the hash algorithm used for the proof.
        hash_algo_field: str = proof_fields[0]
        _, hash_algo = hash_algo_field.split('=')

        # Extract the encoded discrete log parameters.
        encoded_dlog_params: str = proof_fields[1]
        try:
            dlog_params_set = NIZKDiscreteLogParameterSet.from_string_encoding(encoded_dlog_params)
        except ValueError as ve:
            raise ValueError(
                f"Invalid NIZK equal discrete logs proof encoding -- the set of discrete log product/base point pairs"
                f" failed decoding, due to exception: {ve}"
            ) from ve
        else:
            # Set the parameter-set's hash algorithm to the one specified in the proof's encoding.
            dlog_params_set.hash_algo = hash_algo

        # Extract the proof's public hash and signature.
        proof_pub_hash_base64: str = proof_fields[-2]
        proof_signature_base64: str = proof_fields[-1]

        try:
            proof_pub_hash_bytes: bytes = base64.b64decode(proof_pub_hash_base64)
            proof_signature_bytes: bytes = base64.b64decode(proof_signature_base64)

            proof_pub_hash: NIZKEqualDiscreteLogsProofHash = NIZKEqualDiscreteLogsProofHash(
                number.bytes_to_long(proof_pub_hash_bytes)
            )
            proof_signature: NIZKEqualDiscreteLogsProofSignature = NIZKEqualDiscreteLogsProofSignature(
                number.bytes_to_long(proof_signature_bytes)
            )
        except (ValueError, TypeError, binascii.Error) as ex:
            raise ValueError(
                f"Invalid NIZK equal discrete logs proof encoding -- failed to decode the proof's public hash or"
                f" proof signature components from base64-encoded values, due to exception: {ex}"
            ) from ex
        else:
            return NIZKEqualDiscreteLogsProof(
                dlog_params_set,
                proof_pub_hash,
                proof_signature,
                hash_algorithm=hash_algo
            )

    def verify(self) -> bool:
        # Reject an invalid ZK proof (i.e., where the proof's public hash or signature is zero).
        if self.proof_pub_hash == 0 or self.proof_signature == 0:
            return False

        # Reconstruct each nonce point from the corresponding EC base & reference points, and the ZK proof's signature
        # & public hash scalars (as `nonce_pt_i := proof_sig * base_pt_i + proof_pub_hash * ref_pt_i`, for i in [1,N]),
        # according to the Chaum-Pedersen protocol (adapted for discrete logs over elliptic curves).
        nonce_points: list[ECC.EccPoint] = []
        for dlog_base, dlog_ref_point in self.discrete_log_params_set.dlog_base_and_ref_points:
            nonce_point: ECC.EccPoint = dlog_base * self.proof_signature + dlog_ref_point * self.proof_pub_hash

            # A nonce point may not equal the point-at-infinity.
            if nonce_point.is_point_at_infinity():
                return False

            nonce_points.append(nonce_point)

        # Recalculate the ZK proof's public hash via the reconstructed nonce points, and the provided corresponding
        # pairs of EC base & reference points (provided via this ZK proof object's NIZKDiscreteLogParametersSet field).
        expected_pub_hash: NIZKEqualDiscreteLogsProofHash = self.context.calc_public_hash(
            self.discrete_log_params_set,
            nonce_points,
            hash_algorithm=self.hash_algo
        )

        # The ZK proof is valid if the recalculated public hash equals the proof's public hash.
        return expected_pub_hash == self.proof_pub_hash

    def encode_as_string(self) -> str:
        """
        Encodes this NIZK proof of knowledge (PoK) of equal discrete logarithms, including associated discrete log
        parameters, as a colon-delimited string of key=value formatted properties & base64-encoded binary values, as
        follows:
            `hash-algo=<hash-algorithm>:<encoded_dlog_params>:<proof_pub_hash>:<proof_signature>`
        :return: a string encoding of this NIZK proof of knowledge (PoK) of equal discrete logarithms, which uses
                 base64-encoding for binary values.
        """
        encoded_dlog_params: str = self.discrete_log_params_set.encode_as_string()

        proof_signature_bytes: bytes = number.long_to_bytes(self.proof_signature)
        proof_signature_base64: str = base64.b64encode(proof_signature_bytes).decode('utf-8')

        proof_pub_hash_bytes: bytes = number.long_to_bytes(self.proof_pub_hash)
        proof_pub_hash_base64: str = base64.b64encode(proof_pub_hash_bytes).decode('utf-8')

        hash_algo_field: str = f"hash-algo={self.hash_algo}"

        return STRING_ENCODING_FIELD_DELIMITER.join([
            hash_algo_field,
            encoded_dlog_params,
            proof_pub_hash_base64,
            proof_signature_base64
        ])

    def __str__(self) -> str:
        return self.encode_as_string()


class NIZKEqualDiscreteLogsProver:
    curve_config: WeierstrassEllipticCurveConfig
    context: NIZKEqualDiscreteLogsContext
    hash_algo: str

    def __init__(
            self, curve_config: WeierstrassEllipticCurveConfig,
            hash_algorithm: str = NIZKEqualDiscreteLogsContext.DEFAULT_HASH_ALGORITHM
    ):
        self.curve_config = curve_config
        self.context = NIZKEqualDiscreteLogsContext(self.curve_config)
        self.hash_algo = hash_algorithm

    @property
    def order(self) -> int:
        """
        Returns the configured elliptic curve sub-group's order (i.e., the order of the sub-group generated by `G`).
        """
        return self.curve_config.order

    def calc_proof(
            self,
            discrete_log: int,
            discrete_log_params_set: NIZKDiscreteLogParameterSet
    ) -> NIZKEqualDiscreteLogsProof:
        """
        Generates a non-interactive zero-knowledge (NIZK) proof of knowledge (PoK) of N equal discrete logarithms,
        given the (common) discrete logarithm to be proven equal, and a set of N discrete logarithm base/reference point
        pairs (i.e., where `ref_point := dlog * dlog_base`).
        :param discrete_log: the common discrete logarithm (witness) to be proven equal for each base/reference point
               pair.
        :param discrete_log_params_set: a set of N discrete log base/reference point pairs, for which each discrete log
               is to be proven equal.
        :return: a non-interactive zero-knowledge (NIZK) proof of knowledge (PoK) of N equal discrete logarithms.
        """

        # Generate a random nonce repeatedly until a valid ZK proof is constructed, which requires both the (truncated)
        # public hash (as an integer) and the proof signature to be non-zero.
        while True:
            # Generate a private nonce (i.e., ephemeral private key), to be used for this single ZK proof only.
            private_nonce: int = self.context.generate_random_nonce()

            # Construct a nonce point for each provided discrete log base (as `nonce_point := nonce * base_point`),
            # using the same nonce for each point's construction (i.e., a common dlog for each nonce point).
            nonce_points: list[ECC.EccPoint] = []
            for base_point, _ in discrete_log_params_set.dlog_base_and_ref_points:
                nonce_point: ECC.EccPoint = base_point * private_nonce

                # Disallow the point-at-infinity as a nonce point.
                if nonce_point.is_point_at_infinity():
                    break  # Retry nonce generation.

                # Append the valid nonce point to the list of nonce points.
                nonce_points.append(nonce_point)

            # Nonce points generation (for-loop) completed normally (i.e., no break occurred), so proceed.
            else:
                # Ensure the number of nonce points matches the number of dlog base/ref. point pairs.
                if len(nonce_points) != len(discrete_log_params_set.dlog_base_and_ref_points):
                    continue  # Retry nonce generation.

                # Calculate public hash: `H_q( base_pt1, ref_pt1, base_pt2, ref_pt2, ..., nonce_pt1, nonce_pt2, ... )`,
                # where H_q(...) is a cryptographic hash that has been truncated to the bit-length of the configured
                # elliptic curve sub-group's order `q` (i.e., `self.order`).
                pub_hash: NIZKEqualDiscreteLogsProofHash = self.context.calc_public_hash(
                    discrete_log_params_set,
                    nonce_points,
                    hash_algorithm=self.hash_algo
                )
                # Ensure the (truncated) public hash (as an integer) is non-zero, otherwise retry nonce generation.
                if pub_hash == 0:
                    continue  # Retry nonce generation.

                # Calculate the NIZK proof of knowledge (PoK) as: `sig := (ephemeral_key - pub_hash * dlog) mod q`,
                # according to the Chaum-Pedersen protocol (i.e., adapted for discrete logs over elliptic curves &
                # generalized to N equal discrete logs).
                proof_signature = NIZKEqualDiscreteLogsProofSignature(
                    (private_nonce - int(pub_hash) * discrete_log) % self.order
                )

                # Ensure the proof signature is non-zero, otherwise retry nonce generation.
                if proof_signature != 0:
                    # Return the ZK proof, following construction of a valid proof signature.
                    return NIZKEqualDiscreteLogsProof(
                        discrete_log_params_set,
                        pub_hash,
                        proof_signature,
                        hash_algorithm=self.hash_algo
                    )
                # else: Retry nonce generation.
