"""
Provides a non-interactive zero-knowledge (NIZK) proof of knowledge (PoK) of N _equal_ discrete logarithms, over a
prime-order elliptic curve group (e.g., NIST P-256).
- This NIZK proof construction is based on the `Chaum-Pedersen (interactive) protocol
<https://link.springer.com/content/pdf/10.1007/3-540-48071-4_7.pdf>` for proving knowledge in ZK of _two_ equal discrete
logarithms, which has been adapted to operate over elliptic curves and generalized from 2 to N equal discrete logs.
- The `Fiat-Shamir transform <https://en.wikipedia.org/wiki/Fiat%E2%80%93Shamir_heuristic>` is then used to produce a
non-interactive ZK proof construction, featuring both non-interactive proof generation & verification.
"""
from __future__ import annotations

import base64
import hashlib

from typing import NewType, Tuple

from Cryptodome.PublicKey import ECC
from Cryptodome.Util import number

from scriptless_zkp import STRING_ENCODING_FIELD_DELIMITER
from scriptless_zkp.ecc.ecc_utils import generate_random_nonce
from scriptless_zkp.ecc.weierstrass_curves import WeierstrassEllipticCurveConfig

from scriptless_zkp.hashing import PrimeLengthTruncatedHasher


NIZKEqualDiscreteLogsProofSignature = NewType('NIZKEqualDiscreteLogsProofSignature', int)
"""
Efficient type for the NIZK proof's signature, which auto-casts to an `int`, but not from an `int`, providing type
safety in function & method calls (i.e., where other int-typed parameters may be present).
"""

NIZKEqualDiscreteLogsProofHash = NewType('NIZKEqualDiscreteLogsProofHash', int)
"""
Efficient type for the NIZK proof's public hash, which auto-casts to an `int`, but not from an `int, providing type
safety in function & method calls (i.e., where other int-typed parameters may be present).
"""

ECCDiscreteLogBaseAndProduct = NewType('ECCDiscreteLogBaseAndProduct', Tuple[ECC.EccPoint, ECC.EccPoint])
"""
Efficient type for an ECC base point/reference (product) point pair (i.e., where `ref_point := dlog * base_point`),
such that knowledge of the discrete logarithm (witness) being proven is the discrete log of the reference point with
respect to this base point.
"""


class NIZKEqualDiscreteLogsContext:
    DEFAULT_HASH_ALGORITHM: str = hashlib.sha3_256().name  # Note: Suitable for 255 & 256-bit elliptic curves.
    DEFAULT_DOMAIN_SEPARATION_TAG = 'nizk_equal_dlogs_proof'

    curve_config: WeierstrassEllipticCurveConfig
    domain_separator: str

    def __init__(
            self,
            curve_config: WeierstrassEllipticCurveConfig,
            domain_separation_tag: str = DEFAULT_DOMAIN_SEPARATION_TAG
    ):
        self.curve_config = curve_config
        self.domain_separator = domain_separation_tag

    @property
    def curve(self) -> str:
        """Returns the (primary) name of the configured elliptic curve."""
        return self.curve_config.curve

    @property
    def order(self) -> int:
        """
        Returns the configured elliptic curve sub-group's order (i.e., the order of the sub-group generated by `G`).
        """
        return self.curve_config.order

    # noinspection PyPep8Naming
    @property
    def G(self) -> ECC.EccPoint:
        """Returns the configured elliptic curve's generator (base) point."""
        return self.curve_config.base_point

    def calc_public_hash(
            self,
            discrete_log_params_set: NIZKDiscreteLogParameterSet,
            secret_nonce_points: list[ECC.EccPoint],
            hash_algorithm: str
    ) -> NIZKEqualDiscreteLogsProofHash:
        # Verify we have the required nonce point per dlog base/ref. point pair.
        assert len(secret_nonce_points) == len(discrete_log_params_set.dlog_base_and_ref_points)

        # Init. a truncated hasher for hashing to bit-length of elliptic curve sub-group's order (i.e., `|<G>|`), and
        # use a domain separation tag to ensure distinct hashes from other uses of SHA3-256.
        hasher = PrimeLengthTruncatedHasher(
            self.order,
            hash_algorithm=hash_algorithm,
            domain_separation_tag=self.domain_separator
        )

        # Hash each pair of discrete log base and reference points (where each `ref_point := dlog * dlog_base`), using
        # the 'SEC1' binary encoding for each EC point w/out point compression (in order to retain each EC point's
        # y-coordinate's entropy).
        for dlog_base, dlog_ref_point in discrete_log_params_set.dlog_base_and_ref_points:
            hasher.update(self.encode_ecc_point(dlog_base))
            hasher.update(self.encode_ecc_point(dlog_ref_point))

        # Hash each nonce point, following 'SEC1' encoding w/out EC point compression.
        # (Note: There is one nonce point per dlog base/ref point pair.)
        for nonce_point in secret_nonce_points:
            hasher.update(self.encode_ecc_point(nonce_point))

        # Finalize the (possibly) bit-length truncated hash and encode as a big integer.
        pub_hash: int = hasher.intdigest()

        return NIZKEqualDiscreteLogsProofHash(pub_hash)

    @staticmethod
    def encode_public_key(public_key: ECC.EccKey) -> bytes:
        if public_key.has_private():
            return public_key.public_key().export_key(format='SEC1')
        else:
            return public_key.export_key(format='SEC1')

    def encode_ecc_point(self, ecc_point: ECC.EccPoint) -> bytes:
        return self.ecc_point_to_pubkey(ecc_point).export_key(format='SEC1')

    def ecc_point_to_pubkey(self, ecc_point: ECC.EccPoint) -> ECC.EccKey:
        return ECC.construct(curve=self.curve_config.curve, point_x=ecc_point.x, point_y=ecc_point.y)

    def generate_random_nonce(self) -> int:
        """
        Generates a random big integer in the range `[1, q-1]` inclusive, where `q` is the configured elliptic curve
        sub-group's order (i.e., `|<G>|` where `<G>` is the sub-group generated by the public base point `G`).
        :return: a random big integer in the range `[1, q-1]` inclusive, where `q` is the configured elliptic curve
                 sub-group's order.
        """
        return generate_random_nonce(self.curve_config)


class NIZKDiscreteLogParameterSet:
    # Minimum number of discrete log base/ref. point pairs.
    MIN_DISCRETE_LOGS: int = 1  # Note: This protocol generalizes to the single discrete case.

    curve_config: WeierstrassEllipticCurveConfig
    dlog_base_and_ref_points: list[ECCDiscreteLogBaseAndProduct]
    hash_algo: str

    def __init__(
            self,
            curve_config: WeierstrassEllipticCurveConfig,
            dlog_base_and_ref_points: list[ECCDiscreteLogBaseAndProduct],
            hash_algorithm: str = NIZKEqualDiscreteLogsContext.DEFAULT_HASH_ALGORITHM
    ):
        # Ensure the minimum number of dlog base/dlog ref. point pairs were provided.
        assert len(dlog_base_and_ref_points) >= NIZKDiscreteLogParameterSet.MIN_DISCRETE_LOGS

        self.curve_config = curve_config
        self.hash_algo = hash_algorithm
        self.dlog_base_and_ref_points = dlog_base_and_ref_points

    def encode_as_string(self) -> str:
        """
        Encodes this discrete logarithms parameter-set, including the configured elliptic curve's "primary" name, and
        the number of discrete log parameter (dlog base/reference point) pairs, as a colon-delimited string of key=value
        formatted properties & base64-encoded binary values, as follows:
            `curve=<ECC-curve-name>:dlogs-count=<dlogs-count>:<dlog-base-1>:<ref-pt-1>[:<dlog-base-i>:<ref-pt-i>]...`
        """
        context = NIZKEqualDiscreteLogsContext(self.curve_config, self.hash_algo)
        encoded_params: list[str] = []

        # Indicate the configured elliptic curve (by "primary" name).
        curve_name_field: str = f"curve={self.curve_config.curve}"
        encoded_params.append(curve_name_field)

        # Indicate how many discrete logs are being proven equal (i.e., to simplify decoding of the variable-length
        # parameter-set).
        dlogs_count_field: str = f"dlogs_count={len(self.dlog_base_and_ref_points)}"
        encoded_params.append(dlogs_count_field)

        for dlog_base, dlog_ref_point in self.dlog_base_and_ref_points:
            dlog_base_SEC1: bytes = context.encode_ecc_point(dlog_base)
            dlog_base_base64: str = base64.b64encode(dlog_base_SEC1).decode('utf-8')
            encoded_params.append(dlog_base_base64)

            dlog_ref_point_SEC1: bytes = context.encode_ecc_point(dlog_ref_point)
            dlog_ref_point_base64: str = base64.b64encode(dlog_ref_point_SEC1).decode('utf-8')
            encoded_params.append(dlog_ref_point_base64)

        return STRING_ENCODING_FIELD_DELIMITER.join(encoded_params)


class NIZKEqualDiscreteLogsProof:
    context: NIZKEqualDiscreteLogsContext
    discrete_log_params_set: NIZKDiscreteLogParameterSet
    proof_pub_hash: NIZKEqualDiscreteLogsProofHash
    proof_signature: NIZKEqualDiscreteLogsProofSignature
    hash_algo: str

    def __init__(
            self,
            discrete_log_params_set: NIZKDiscreteLogParameterSet,
            proof_public_hash: NIZKEqualDiscreteLogsProofHash,
            proof_signature: NIZKEqualDiscreteLogsProofSignature,
            hash_algorithm: str
    ):
        self.curve_config = discrete_log_params_set.curve_config
        self.hash_algo = hash_algorithm
        self.context = NIZKEqualDiscreteLogsContext(discrete_log_params_set.curve_config)
        self.discrete_log_params_set = discrete_log_params_set
        self.proof_pub_hash = proof_public_hash
        self.proof_signature = proof_signature

    def verify(self) -> bool:
        # Reconstruct each nonce point from the corresponding EC base & reference points, and the ZK proof's signature
        # & public hash scalars (as `nonce_pt_i := proof_sig * base_pt_i + proof_pub_hash * ref_pt_i`, for i in [1,N]),
        # according to the Chaum-Pedersen protocol (adapted for discrete logs over elliptic curves).
        nonce_points: list[ECC.EccPoint] = []
        for dlog_base, dlog_ref_point in self.discrete_log_params_set.dlog_base_and_ref_points:
            nonce_point: ECC.EccPoint = dlog_base * self.proof_signature + dlog_ref_point * self.proof_pub_hash
            nonce_points.append(nonce_point)

        # Recalculate the ZK proof's public hash via the reconstructed nonce points, and the provided corresponding
        # pairs of EC base & reference points (provided via this ZK proof object's NIZKDiscreteLogParametersSet field).
        expected_pub_hash: NIZKEqualDiscreteLogsProofHash = self.context.calc_public_hash(
            self.discrete_log_params_set,
            nonce_points,
            hash_algorithm=self.hash_algo
        )

        # The ZK proof is valid if the recalculated public hash equals the proof's public hash.
        return expected_pub_hash == self.proof_pub_hash

    def encode_as_string(self) -> str:
        """
        Encodes this NIZK proof of knowledge (PoK) of equal discrete logarithms, including associated discrete log
        parameters, as a colon-delimited string of key=value formatted properties & base64-encoded binary values, as
        follows:
            `hash-algo=<hash-algorithm>:<encoded_dlog_params>:<proof_pub_hash>:<proof_signature>`
        :return: a string encoding of this NIZK proof of knowledge (PoK) of equal discrete logarithms, which uses
                 base64-encoding for binary values.
        """
        encoded_dlog_params: str = self.discrete_log_params_set.encode_as_string()

        proof_signature_bytes: bytes = number.long_to_bytes(self.proof_signature)
        proof_signature_base64: str = base64.b64encode(proof_signature_bytes).decode('utf-8')

        proof_pub_hash_bytes: bytes = number.long_to_bytes(self.proof_pub_hash)
        proof_pub_hash_base64: str = base64.b64encode(proof_pub_hash_bytes).decode('utf-8')

        hash_algo_field: str = f"hash-algo={self.hash_algo}"

        return STRING_ENCODING_FIELD_DELIMITER.join([
            hash_algo_field,
            encoded_dlog_params,
            proof_pub_hash_base64,
            proof_signature_base64
        ])


class NIZKEqualDiscreteLogsProver:
    curve_config: WeierstrassEllipticCurveConfig
    context: NIZKEqualDiscreteLogsContext
    hash_algo: str

    def __init__(
            self, curve_config: WeierstrassEllipticCurveConfig,
            hash_algorithm: str = NIZKEqualDiscreteLogsContext.DEFAULT_HASH_ALGORITHM
    ):
        self.curve_config = curve_config
        self.context = NIZKEqualDiscreteLogsContext(self.curve_config)
        self.hash_algo = hash_algorithm

    @property
    def order(self) -> int:
        """
        Returns the configured elliptic curve sub-group's order (i.e., the order of the sub-group generated by `G`).
        """
        return self.curve_config.order

    def calc_proof(
            self,
            discrete_log: int,
            discrete_log_params_set: NIZKDiscreteLogParameterSet
    ) -> NIZKEqualDiscreteLogsProof:
        # Generate a private nonce (i.e., ephemeral private key), to be used for this single ZK proof only.
        private_nonce: int = self.context.generate_random_nonce()

        # Construct a nonce point for each provided discrete log base (as `nonce_point := nonce * base_point`),
        # using the same nonce for each point's construction (i.e., a common dlog for each nonce point).
        nonce_points: list[ECC.EccPoint] = []
        for base_point, _ in discrete_log_params_set.dlog_base_and_ref_points:
            nonce_point: ECC.EccPoint = base_point * private_nonce
            nonce_points.append(nonce_point)

        # Calculate the public hash as: `H_q( base_pt1, ref_pt1, base_pt2, ref_pt2, ..., nonce_pt1, nonce_pt2, ... )`,
        # where H_q(...) is a cryptographic hash that has been truncated to the bit-length of the configured elliptic
        # curve sub-group's order `q` (i.e., `self.order`).
        pub_hash: NIZKEqualDiscreteLogsProofHash = self.context.calc_public_hash(
            discrete_log_params_set,
            nonce_points,
            hash_algorithm=self.hash_algo
        )

        # Calculate the NIZK proof of knowledge (PoK) (as: `sig := (ephemeral_key - pub_hash * dlog) mod q`), according
        # to the Chaum-Pedersen protocol (adapted for discrete logs over elliptic curves).
        proof_signature: int = (private_nonce - int(pub_hash) * discrete_log) % self.order

        return NIZKEqualDiscreteLogsProof(
            discrete_log_params_set,
            pub_hash,
            NIZKEqualDiscreteLogsProofSignature(proof_signature),
            hash_algorithm=self.hash_algo
        )
