[project]
name = "scriptless_zkp"
version = "0.4.0"
authors = [
  { name="qubits4all", email="qubits4all@users.noreply.github.com" },
]
maintainers = [
  { name="qubits4all", email="qubits4all@users.noreply.github.com" },
]
description = 'Scriptless-ZKP - Adaptor & multi-party signatures, zero-knowledge proofs (ZKPs) & "scriptless" scripts'
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.11"
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/qubits4all/scriptless-zkp"
Repository = "https://github.com/qubits4all/scriptless-zkp.git"
Issues = "https://github.com/qubits4all/scriptless-zkp/issues"

[tool.poetry]
name = "scriptless_zkp"
version = "0.4.0"
description = 'Scriptless-ZKP - Adaptor & multi-party signatures, zero-knowledge proofs (ZKPs) & "scriptless" scripts'
authors = ["qubits4all <qubits4all@users.noreply.github.com>"]

packages = [
    { include = "src/python" },
    { include = "src/python/**/*.py" },
]

[tool.poetry.dependencies]
python = "^3.11"
attrs = "~23.2.0"
pycryptodomex = "~3.20.0"
libnum = "~1.7.1"

# Transitive dependencies:
certifi = "^2024.7.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"
