"""
This module provides an abstract base class for elliptic curve configuration classes, which features methods for
validating elliptic curve points, obtaining an elliptic curve's base (public generator) point, obtaining and checking
for the identity (point-at-infinity) point, and encoding & decoding elliptic curve points.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

import math

from scriptless_zkp.ecc.points import EccPoint2D


class EllipticCurveConfig(ABC):
    """
    Configuration context for working with elliptic curves used in elliptic curve cryptography (ECC).
    Support for obtaining a curve's base point (or generator) is provided, as well as frequently needed properties for
    the order of the sub-group generated by this base point, the order of the field the elliptic curve points'
    coordinates are over, and other intrinsic properties of a given elliptic curve.
    """

    curve: str
    """A primary name used to identify this elliptic curve, which may be a commonly-used abbreviated form."""

    order: int
    """
    The prime order (`q`) of the sub-group generated by the common, public base point (generator) of this elliptic
    curve.
    """

    modulus: int
    """
    The prime order (`p`) of the field (`F_p`) this elliptic curve's points' coordinates and its elliptic curve
    equation's coefficients `a` and `b` are in.
    """

    base_point: EccPoint2D
    """
    A common, public base point (generator) `G` of the elliptic curve, which generates a cyclic sub-group `<G>` of
    order ``self.order``.
    """

    cofactor: int
    """
    The cofactor (`h`) of the elliptic curve, which is the ratio of the order of the elliptic curve group (`E(F_p)`) to
    the order of the sub-group (`<G>`) generated by its public base point (`G`) (i.e., `h = |E(F_p)| / |<G>|`).
    """

    size_bits: int
    """
    Size of this elliptic curve's sub-group in bits, the bit-length of the order of the sub-group generated by the
    curve's common, public base point (generator).
    """

    curve_aliases: list[str]
    """A list of one or more aliases this elliptic curve is known by, including the primary name given by `curve`."""

    @abstractmethod
    def __init__(
            self,
            curve: str,
            order: int,
            modulus: int,
            base_point: EccPoint2D,
            cofactor: int, size_bits: int,
            curve_aliases: list[str]
    ):
        """
        Initializes a new elliptic curve configuration context with the specified curve name, order, modulus, cofactor,
        size in bits, and a list of aliases this elliptic curve is known by.

        :param curve: the name of the elliptic curve.
        :param order: the (prime) order of the cyclic sub-group generated by the curve's base point `G`.
        :param modulus: the prime order of the field the curve's points' coordinates are in.
        :param base_point: the common, public base point (generator) `G` of the elliptic curve's cyclic sub-group `<G>`.
        :param cofactor: the cofactor of the elliptic curve.
        :param size_bits: the bit-length of the order of the curve's sub-group.
        :param curve_aliases: a list of one or more aliases this elliptic curve is known by.
        """
        self.curve = curve
        self.order = order
        self.modulus = modulus
        self.base_point = base_point
        self.cofactor = cofactor
        self.size_bits = size_bits
        self.curve_aliases = curve_aliases

    @property
    def curve_size_bytes(self) -> int:
        """
        Size of this elliptic curve's sub-group in bytes, the byte-length of the order of the sub-group generated by the
        curve's public base point (generator) `G`.
        """
        return math.ceil(self.size_bits / 8)

    # noinspection PyPep8Naming
    @property
    def G(self) -> EccPoint2D:
        """
        Returns the public base point (generator) `G` of the elliptic curve, which generates a cyclic sub-group `<G>`
        of order ``self.order``.
        :return: the public base point (generator) `G` of the elliptic curve.
        """
        return self.base_point

    def is_identity(self, point: EccPoint2D) -> bool:
        """
        Returns whether the given elliptic curve point is the point-at-infinity (`O`), the group's additive identity.
        :return whether this point is the identity element (i.e., the point-at-infinity).
        """
        return self.is_point_at_infinity(point)

    @abstractmethod
    def is_point_at_infinity(self, point: EccPoint2D) -> bool:
        """
        Returns whether the given elliptic curve point is the point-at-infinity (`O`), the group's additive identity.
        :return whether this point is the point-at-infinity.
        """
        pass

    def has_curve_name(self, curve_name: str) -> bool:
        """
        Returns whether the given name matches a known alias of this Weierstrass elliptic curve configuration context.
        :param curve_name: the name or alias of the elliptic curve to check against this configuration instance.
        :return: whether the given name matches a known alias of this Weierstrass elliptic curve configuration context.
        """
        return curve_name in self.curve_aliases

    @abstractmethod
    def is_point_on_curve(self, point: EccPoint2D) -> bool:
        """
        Returns whether the given elliptic curve point is on this curve, inclusive of the point-at-infinity, by
        verifying the point's x and y coordinates satisfy the elliptic curve's equation.
        """
        pass

    @abstractmethod
    def serialize_point(self, point: EccPoint2D, compress: bool = False) -> bytes:
        """
        Serialize the given elliptic curve point to a byte string (e.g., using the SEC1 encoding format).
        :param point: the elliptic curve point to serialize.
        :param compress: whether to serialize the point in compressed form.
        :return: the serialized byte string representation of the elliptic curve point (possibly compressed).
        """
        pass

    @abstractmethod
    def deserialize_point(self, serialized_point: bytes) -> EccPoint2D:
        """
        Deserialize the given byte string representation of an elliptic curve point to an elliptic curve point instance.
        :param serialized_point: the byte string representation of the elliptic curve point to deserialize
               (e.g., provided in the SEC1 encoding format).
        :return: the deserialized elliptic curve point instance.
        :raises ValueError: if the provided serialized point is in an invalid format, or if the deserialized elliptic
                curve point is not on the elliptic curve specified by this elliptic curve configuration context.
        """
        pass

    @property
    @abstractmethod
    def identity(self) -> EccPoint2D:
        pass

    @classmethod
    @abstractmethod
    def for_curve_name(cls, curve_name: str) -> EllipticCurveConfig:
        """
        Retrieve an elliptic curve configuration context for the specified curve name.
        :param curve_name: the name of the elliptic curve to retrieve a configuration instance for.
        :return: an elliptic curve configuration context for the specified curve name.
        """
        pass

    @classmethod
    @abstractmethod
    def is_curve_supported(cls, curve_name: str) -> bool:
        pass
