"""
This module provides an abstract base class for elliptic curve configuration classes, which features methods for
validating elliptic curve points, obtaining an elliptic curve's base (public generator) point, obtaining and checking
for the identity (point-at-infinity) point, and encoding & decoding elliptic curve points.
"""

from __future__ import annotations

from abc import ABC, abstractmethod

import math

from scriptless_zkp.ecc.points import ECCPoint2D, WeierstrassPoint2D, SECP256K1Point2D


class EllipticCurveContext(ABC):
    """
    Configuration context for working with elliptic curves used in elliptic curve cryptography (ECC).
    Support for obtaining a curve's base point (or generator) is provided, as well as frequently needed properties for
    the order of the sub-group generated by this base point, the order of the field the elliptic curve points'
    coordinates are over, and other intrinsic properties of a given elliptic curve.
    """

    curve: str
    """A primary name used to identify this elliptic curve, which may be a commonly-used abbreviated form."""

    order: int
    """
    The prime order (`q`) of the sub-group generated by the common, public base point (generator) of this elliptic
    curve.
    """

    modulus: int
    """
    The prime order (`p`) of the field (`F_p`) this elliptic curve's points' coordinates and its elliptic curve
    equation's coefficients `a` and `b` are in.
    """

    base_point: ECCPoint2D
    """
    A common, public base point (generator) `G` of the elliptic curve, which generates a cyclic sub-group `<G>` of
    order ``self.order``.
    """

    cofactor: int
    """
    The cofactor (`h`) of the elliptic curve, which is the ratio of the order of the elliptic curve group (`E(F_p)`) to
    the order of the sub-group (`<G>`) generated by its public base point (`G`) (i.e., `h = |E(F_p)| / |<G>|`).
    """

    size_bits: int
    """
    Size of this elliptic curve's sub-group in bits, the bit-length of the order of the sub-group generated by the
    curve's common, public base point (generator).
    """

    curve_aliases: list[str]
    """A list of one or more aliases this elliptic curve is known by, including the primary name given by `curve`."""

    @abstractmethod
    def __init__(
            self,
            curve: str,
            order: int,
            modulus: int,
            base_point: ECCPoint2D,
            cofactor: int,
            size_bits: int,
            curve_aliases: list[str]
    ):
        """
        Initializes a new elliptic curve configuration context with the specified curve name, order, modulus, cofactor,
        size in bits, and a list of aliases this elliptic curve is known by.

        :param curve: the name of the elliptic curve.
        :param order: the (prime) order of the cyclic sub-group generated by the curve's base point `G`.
        :param modulus: the prime order of the field the curve's points' coordinates are in.
        :param base_point: the common, public base point (generator) `G` of the elliptic curve's cyclic sub-group `<G>`.
        :param cofactor: the cofactor of the elliptic curve.
        :param size_bits: the bit-length of the order of the curve's sub-group.
        :param curve_aliases: a list of one or more aliases this elliptic curve is known by.
        """
        self.curve = curve
        self.order = order
        self.modulus = modulus
        self.base_point = base_point
        self.cofactor = cofactor
        self.size_bits = size_bits
        self.curve_aliases = curve_aliases

    @classmethod
    def secp256r1(cls) -> WeierstrassEllipticCurveContext:
        return WeierstrassEllipticCurveContext.secp256r1()

    @classmethod
    def p256(cls) -> WeierstrassEllipticCurveContext:
        return WeierstrassEllipticCurveContext.secp256r1()

    @classmethod
    def secp256k1(cls) -> SECP256K1EllipticCurveContext:
        return SECP256K1EllipticCurveContext.secp256k1()

    @classmethod
    def p256k1(cls) -> SECP256K1EllipticCurveContext:
        return SECP256K1EllipticCurveContext.secp256k1()

    @property
    def curve_size_bytes(self) -> int:
        """
        Size of this elliptic curve's sub-group in bytes, the byte-length of the order of the sub-group generated by the
        curve's public base point (generator) `G`.
        """
        return math.ceil(self.size_bits / 8)

    # noinspection PyPep8Naming
    @property
    def G(self) -> ECCPoint2D:
        """
        Returns the public base point (generator) `G` of the elliptic curve, which generates a cyclic sub-group `<G>`
        of order ``self.order``.
        :return: the public base point (generator) `G` of the elliptic curve.
        """
        return self.base_point

    @property
    def q(self) -> int:
        return self.order

    @property
    def p(self) -> int:
        return self.modulus

    @property
    def h(self) -> int:
        return self.cofactor

    @abstractmethod
    def __str__(self) -> str:
        """
        Returns a string-encoding of this elliptic curve configuration context, including the curve name and its
        primary properties.
        """
        pass

    @abstractmethod
    def __repr__(self) -> str:
        """
        Returns a string representation of this elliptic curve configuration context, including the curve name and its
        primary properties.
        """
        pass

    def is_identity(self, point: ECCPoint2D) -> bool:
        """
        Returns whether the given elliptic curve point is the point-at-infinity (`O`), the group's additive identity.
        :return whether this point is the identity element (i.e., the point-at-infinity).
        """
        return self.is_point_at_infinity(point)

    @abstractmethod
    def is_point_at_infinity(self, point: ECCPoint2D) -> bool:
        """
        Returns whether the given elliptic curve point is the point-at-infinity (`O`), the group's additive identity.
        :return whether this point is the point-at-infinity.
        """
        pass

    def has_curve_name(self, curve_name: str) -> bool:
        """
        Returns whether the given name matches a known alias of this Weierstrass elliptic curve configuration context.
        :param curve_name: the name or alias of the elliptic curve to check against this configuration instance.
        :return: whether the given name matches a known alias of this Weierstrass elliptic curve configuration context.
        """
        return curve_name in self.curve_aliases

    @abstractmethod
    def is_point_on_curve(self, point: ECCPoint2D) -> bool:
        """
        Returns whether the given elliptic curve point is on this curve, inclusive of the point-at-infinity, by
        verifying the point's x and y coordinates satisfy the elliptic curve's equation.
        """
        pass

    @abstractmethod
    def serialize_point(self, point: ECCPoint2D, compress: bool = False) -> bytes:
        """
        Serialize the given elliptic curve point to a byte string (e.g., using the SEC1 encoding format).
        :param point: the elliptic curve point to serialize.
        :param compress: whether to serialize the point in compressed form.
        :return: the serialized byte string representation of the elliptic curve point (possibly compressed).
        """
        pass

    @abstractmethod
    def deserialize_point(self, serialized_point: bytes) -> ECCPoint2D:
        """
        Deserialize the given byte string representation of an elliptic curve point to an elliptic curve point instance.
        :param serialized_point: the byte string representation of the elliptic curve point to deserialize
               (e.g., provided in the SEC1 encoding format).
        :return: the deserialized elliptic curve point instance.
        :raises ValueError: if the provided serialized point is in an invalid format, or if the deserialized elliptic
                curve point is not on the elliptic curve specified by this elliptic curve configuration context.
        """
        pass

    @property
    @abstractmethod
    def identity(self) -> ECCPoint2D:
        pass

    @classmethod
    @abstractmethod
    def for_curve_name(cls, curve_name: str) -> EllipticCurveContext | None:
        """
        Retrieve an elliptic curve configuration context for the specified curve name.
        :param curve_name: the name of the elliptic curve to retrieve a configuration instance for.
        :return: an elliptic curve configuration context for the specified curve name.
        """
        pass

    @classmethod
    @abstractmethod
    def is_curve_supported(cls, curve_name: str) -> bool:
        pass


class WeierstrassEllipticCurveContext(EllipticCurveContext):
    """
    Configuration context for working with Weierstrass elliptic curves used in elliptic curve cryptography (ECC).
    """
    _a: int
    _b: int

    def __init__(
            self,
            curve: str,
            order: int,
            modulus: int,
            coeff_a: int,
            coeff_b: int,
            base_point: WeierstrassPoint2D,
            cofactor: int,
            size_bits: int,
            curve_aliases: list[str]
    ):
        super().__init__(curve, order, modulus, base_point, cofactor, size_bits, curve_aliases)
        self._a = coeff_a
        self._b = coeff_b

    @classmethod
    def for_curve_name(cls, curve_name: str) -> WeierstrassEllipticCurveContext | None:
        """
        Factory function for constructing a configuration context for a supported elliptic curve, given its common name
        or alias; otherwise returning `None` if the provided curve name is not a supported curve.
        :param curve_name: The primary name or alias of a supported elliptic curve.
        :return: A configuration context for a supported elliptic curve; or `None` if the named curve is unsupported.
        """
        # Check if provided elliptic curve name is a primary name for a supported curve.
        if curve_name in cls._supported_curve_aliases():
            return cls._curve_by_primary_name(curve_name)
        else:  # otherwise check if provided curve name is an alias for a supported curve
            for curve, aliases in cls._supported_curve_aliases().items():
                if curve_name in aliases:
                    return cls._curve_by_primary_name(curve)
            else:  # provided curve name is not a primary name or alias for a supported curve
                return None

    @classmethod
    def _curve_by_primary_name(cls, primary_curve_name: str) -> WeierstrassEllipticCurveContext | None:
        """
        Returns an elliptic curve configuration context given the curve's primary name, if it is a supported curve;
        otherwise, returns `None`.
        :param primary_curve_name: The primary name of a supported elliptic curve.
        :return: A configuration context for a supported elliptic curve, given its primary name; or `None` if
                 unsupported.
        """
        match primary_curve_name:
            case "P-256":
                return cls.p256()
            # case "P-384":
            #     return cls.p384()
            # case "P-521":
            #     return cls.p521()
            case _:  # unsupported curve
                return None

    @classmethod
    def secp256r1(cls) -> WeierstrassEllipticCurveContext:
        base_point = WeierstrassPoint2D(
            curve_name="P-256",
            x=0x6B17D1F2_E12C4247_F8BCE6E5_63A440F2_77037D81_2DEB33A0_F4A13945_D898C296,  # big-endian
            y=0x4FE342E2_FE1A7F9B_8EE7EB4A_7C0F9E16_2BCE3357_6B315ECE_CBB64068_37BF51F5   # big-endian
        )

        return cls(
            curve="P-256",
            order=0xFFFFFFFF_00000000_FFFFFFFF_FFFFFFFF_BCE6FAAD_A7179E84_F3B9CAC2_FC632551,
            modulus=0xFFFFFFFF_00000001_00000000_00000000_00000000_FFFFFFFF_FFFFFFFF_FFFFFFFF,  # p = 2^256 - 2^224 + 2^192 + 2^96 - 1
            coeff_a=0xFFFFFFFF_00000001_00000000_00000000_00000000_FFFFFFFF_FFFFFFFF_FFFFFFFC,  # -3 mod p
            coeff_b=0X5AC635D8_AA3A93E7_B3EBBD55_769886BC_651D06B0_CC53B0F6_3BCE3C3E_27D2604B,
            base_point=base_point,
            cofactor=1,
            size_bits=256,
            curve_aliases=["p256", "NIST P-256", "P-256", "prime256v1", "secp256r1", "nistp256"]
        )

    @classmethod
    def p256(cls) -> WeierstrassEllipticCurveContext:
        return cls.secp256r1()

    @classmethod
    def is_curve_supported(cls, curve_name: str) -> bool:
        """
        Returns whether the provided elliptic curve common/primary name or alias is supported.
        """
        # Check if provided elliptic curve name is a primary name for a supported curve.
        return curve_name in cls._supported_curve_aliases() or (
            # Otherwise, check if provided curve name is an alias for a supported curve.
            any(
                curve_name in aliases for aliases in cls._supported_curve_aliases().values()
            )
        )

    @staticmethod
    def _supported_curve_aliases() -> dict[str, list[str]]:
        """
        Returns a dictionary of supported elliptic curve names, where each key is the primary name for a supported
        curve, and the value is a list of aliases for that curve.
        :return: A dictionary of supported elliptic curve aliases keyed by a curve's primary name.
        """
        return {
            'P-256': ["P-256", "NIST P-256", "secp256r1", "prime256v1", "nistp256", "p256"],
            # 'P-384': ["P-384", "NIST P-384", "secp384r1", "prime384v1", "nistp384", "p384"],
            # 'P-521': ["P-521", "NIST P-521", "secp521r1", "prime521v1", "nistp521", "p521"]
        }

    @property
    def identity(self) -> WeierstrassPoint2D:
        return WeierstrassPoint2D.identity(self.curve)

    @property
    def coeff_a(self) -> int:
        return self._a

    @property
    def coeff_b(self) -> int:
        return self._b

    def __str__(self) -> str:
        return self.__repr__()

    def __repr__(self) -> str:
        return (
            f"WeierstrassEllipticCurveContext(curve='{self.curve}', order={self.order}, modulus={self.modulus}, "
            f"coeff_a={self._a}, coeff_b={self._b}, base_point={self.base_point!s}, cofactor={self.cofactor}, "
            f"size_bits={self.size_bits}, curve_aliases={self.curve_aliases})"
        )

    def is_point_at_infinity(self, point: WeierstrassPoint2D) -> bool:
        return point.is_point_at_infinity()

    def is_point_on_curve(self, point: WeierstrassPoint2D) -> bool:
        """
        Returns whether the given elliptic curve point is on this curve, inclusive of the point-at-infinity, by
        verifying the point's x and y coordinates satisfy the Weierstrass elliptic curve equation:
        `y² = x³ + ax + b mod p`, where `p` is the prime modulus of the curve `E(F_p)` over the finite field `F_p` and
        `a` and `b` are the curve's defined coefficients.

        Note: The point-at-infinity (identity element `O`) is always considered to be "on the curve", and isn't checked
          via the elliptic curve equation.

        :param point: The elliptic curve point to verify for membership on this elliptic curve configuration's curve.
        :return: `True` if the point is on the curve; `False` otherwise.
        """
        if point.is_point_at_infinity():
            return True

        # Verify point's (x, y) coordinates satisfy the Weierstrass elliptic curve equation: `y² = x³ + ax + b mod p`
        x, y = point.x, point.y
        return (y * y) % self.modulus == (x * x * x + self._a * x + self._b) % self.modulus

    def serialize_point(self, point: WeierstrassPoint2D, compress: bool = False) -> bytes:
        return point.serialize(compress=compress)

    def deserialize_point(self, serialized_point: bytes) -> WeierstrassPoint2D:
        return WeierstrassPoint2D.deserialize(self.curve, serialized_point)


class SECP256K1EllipticCurveContext(EllipticCurveContext):
    _b: int

    def __init__(
            self,
            curve: str,
            order: int,
            modulus: int,
            coeff_b: int,
            base_point: SECP256K1Point2D,
            cofactor: int,
            size_bits: int,
            curve_aliases: list[str]
    ):
        super().__init__(curve, order, modulus, base_point, cofactor, size_bits, curve_aliases)
        self._b = coeff_b

    @classmethod
    def for_curve_name(cls, curve_name: str) -> SECP256K1EllipticCurveContext | None:
        """
        Factory function for constructing a configuration context for a supported elliptic curve, given its common name
        or alias; otherwise returning `None` if the provided curve name is not a supported curve.
        :param curve_name: The primary name or alias of a supported elliptic curve.
        :return: A configuration context for a supported elliptic curve; or `None` if the named curve is unsupported.
        """
        # Check if provided elliptic curve name is a primary name for a supported curve.
        if curve_name in cls._supported_curve_aliases():
            return cls._curve_by_primary_name(curve_name)
        else:  # otherwise check if provided curve name is an alias for a supported curve
            for curve, aliases in cls._supported_curve_aliases().items():
                if curve_name in aliases:
                    return cls._curve_by_primary_name(curve)
            else:  # provided curve name is not a primary name or alias for a supported curve
                return None

    @classmethod
    def _curve_by_primary_name(cls, primary_curve_name: str) -> SECP256K1EllipticCurveContext | None:
        """
        Returns an elliptic curve configuration context given the curve's primary name, if it is a supported curve;
        otherwise, returns `None`.
        :param primary_curve_name: The primary name of a supported elliptic curve.
        :return: A configuration context for a supported elliptic curve, given its primary name; or `None` if
                 unsupported.
        """
        match primary_curve_name:
            case "secp256k1":
                return cls.secp256k1()
            case _:  # unsupported curve
                return None

    @classmethod
    def secp256k1(cls) -> SECP256K1EllipticCurveContext:
        base_point = SECP256K1Point2D(
            x=0x79BE667E_F9DCBBAC_55A06295_CE870B07_029BFCDB_2DCE28D9_59F2815B_16F81798,
            y=0x483ADA77_26A3C465_5DA4FBFC_0E1108A8_FD17B448_A6855419_9C47D08FF_B10D4B8,
        )

        return SECP256K1EllipticCurveContext(
            curve="secp256k1",
            order=0xFFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFE_BAAEDCE6_AF48A03B_BFD25E8C_D0364141,
            modulus=0xFFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFF_FFFFFFFE_FFFFFC2F,  # p = 2^256 − 2^32 − 2^9 − 2^8 − 2^7 − 2^6 − 2^4 − 1
            coeff_b=0x00000000_00000000_00000000_00000000_00000000_00000000_00000000_00000007,  # 7 in `y² = x³ + 7 mod p`
            base_point=base_point,
            cofactor=1,
            size_bits=256,
            curve_aliases=["secp256k1", "p256k1", "prime256k1", "ansip256k1"]
        )

    @classmethod
    def p256k1(cls) -> SECP256K1EllipticCurveContext:
        return cls.secp256k1()

    @classmethod
    def is_curve_supported(cls, curve_name: str) -> bool:
        """
        Returns whether the provided elliptic curve common/primary name or alias is supported.
        """
        # Check if provided elliptic curve name is a primary name for a supported curve.
        return curve_name in cls._supported_curve_aliases() or (
            # Otherwise, check if provided curve name is an alias for a supported curve.
            any(
                curve_name in aliases for aliases in cls._supported_curve_aliases().values()
            )
        )

    @staticmethod
    def _supported_curve_aliases() -> dict[str, list[str]]:
        """
        Returns a dictionary of supported elliptic curve names, where each key is the primary name for a supported
        curve, and the value is a list of aliases for that curve.
        :return: A dictionary of supported elliptic curve aliases keyed by a curve's primary name.
        """
        return {
            'secp256k1': ["secp256k1", "p256k1", "prime256k1", "ansip256k1"],
        }

    @property
    def identity(self) -> SECP256K1Point2D:
        return SECP256K1Point2D.identity(self.curve)

    @property
    def coeff_a(self) -> int:
        return 0

    @property
    def coeff_b(self) -> int:
        return self._b

    def __str__(self) -> str:
        return self.__repr__()

    def __repr__(self) -> str:
        return (
            f"SECP256K1EllipticCurveContext(curve='{self.curve}', order={self.order}, modulus={self.modulus}, "
            f"coeff_b={self._b}, base_point={self.base_point!s}, cofactor={self.cofactor}, size_bits={self.size_bits}, "
            f"curve_aliases={self.curve_aliases})"
        )

    def is_point_at_infinity(self, point: SECP256K1Point2D) -> bool:
        return point.is_point_at_infinity()

    def is_point_on_curve(self, point: SECP256K1Point2D) -> bool:
        """
        Returns whether the given elliptic curve point is on this curve, inclusive of the point-at-infinity, by
        verifying the point's x and y coordinates satisfy the Koblitz elliptic curve equation: `y² = x³ + b mod p`
        (i.e., essentially a Weierstrass elliptic curve: `y² = x³ + ax + b mod p` with coefficient a=0), where `p` is
        the prime modulus of the curve `E(F_p)` over the finite field `F_p` and `b` is the curve's defined coefficient.

        Note: The point-at-infinity (identity element `O`) is always considered to be "on the curve", and isn't checked
          via the elliptic curve equation.

        :param point: The elliptic curve point to verify for membership on this elliptic curve configuration's curve.
        :return: `True` if the point is on the curve; `False` otherwise.
        """
        if point.is_point_at_infinity():
            return True

        # Verify point's (x, y) coordinates satisfy the Koblitz elliptic curve equation: `y² = x³ + b mod p`
        x, y = point.x, point.y
        return (y * y) % self.modulus == (x * x * x + self._b) % self.modulus

    def serialize_point(self, point: SECP256K1Point2D, compress: bool = False) -> bytes:
        return point.serialize(compress=compress)

    def deserialize_point(self, serialized_point: bytes) -> SECP256K1Point2D:
        return SECP256K1Point2D.deserialize(self.curve, serialized_point)
