"""
Helper functions for working with the elliptic curves used in elliptic curve cryptography (ECC).
"""
from __future__ import annotations

from typing import Optional

from Cryptodome.PublicKey import ECC
from Cryptodome.Random import random

from scriptless_zkp.ecc.weierstrass_curves import WeierstrassEllipticCurveConfig


def generate_random_nonce(curve_config: WeierstrassEllipticCurveConfig) -> int:
    """
    Generates a random big integer in the range `[1, q-1]` inclusive, where `q` is the configured elliptic curve
    sub-group's order (i.e., `|<G>|` where `<G>` is the sub-group generated by the public base point `G`).
    :param curve_config: elliptic curve configuration to be used when generating the random private nonce scalar.
    :return: a random big integer in the range `[1, q-1]` inclusive, where `q` is the configured elliptic curve
             sub-group's order.
    """
    return random.randint(1, curve_config.order - 1)


def generate_random_nonce_pair(
        curve_config: WeierstrassEllipticCurveConfig,
        ecc_base_point: Optional[ECC.EccPoint] = None
) -> (int, ECC.EccPoint):
    """
    Generates a random private nonce scalar (big integer) and an associated nonce elliptic curve (EC) point, constructed
    using the provided EC base point (as `nonce_point := nonce * base_point`), defaulting to the configured elliptic
    curve's public generator `G` if an EC base point is not provided.
    :param curve_config: elliptic curve configuration to be used when generating the random nonce EC point.
    :param ecc_base_point: the ECC base point to be used for constructing the nonce EC point
           (as `nonce_point := nonce * base_point`), defaulting to the configured elliptic curve sub-group's
           generator `G` if not provided.
    :return: (int, ECC.EccPoint) a randomly-generated nonce and an associated nonce EC point, constructed using
             the provided EC base point (or the configured curve's public generator `G` if not provided).
    """
    base_point: ECC.EccPoint = ecc_base_point if ecc_base_point else curve_config.base_point
    private_nonce: int = generate_random_nonce(curve_config)  # random big integer in range [1, order] inclusive
    nonce_point: ECC.EccPoint = base_point * private_nonce

    return private_nonce, nonce_point
