###############################################################################
# (c) 2024 W. Spann Systems Consulting
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

"""
Support classes and helper functions for working with the elliptic curves used in elliptic curve cryptography (ECC).
"""
from __future__ import annotations

import math

from attr import define

from Cryptodome.PublicKey import ECC


@define(slots=True, frozen=True)
class WeierstrassEllipticCurveConfig:
    """
    Configuration context for working with elliptic curves used in elliptic curve cryptography (ECC).
    Support for obtaining a curve's base point (or generator) is provided, as well as frequently needed properties for
    the order of the sub-group generated by this base point, the order of the field the elliptic curve points'
    coordinates are over, and other intrinsic properties of a given elliptic curve.
    """
    curve: str
    """A primary name used to identify this elliptic curve, which may be a commonly-used abbreviated form."""

    order: int
    """
    The prime order (`q`) of the sub-group generated by the common, public base point (generator) of this elliptic
    curve.
    """

    modulus: int
    """
    The prime order (`p`) of the field (`F_p`) this elliptic curve's points' coordinates and its elliptic curve
    equation's coefficients `a` and `b` are in.
    """

    cofactor: int
    """
    The cofactor (`h`) of the elliptic curve, which is the ratio of the order of the elliptic curve group (`E(F_p)`) to
    the order of the sub-group (`<G>`) generated by its public base point (`G`) (i.e., `h = |E(F_p)| / |<G>|`).
    """

    coeff_a: int
    """This elliptic curve's coefficient `a`, in the Weierstrass elliptic curve equation: `y² = x³ + ax + b`"""

    coeff_b: int
    """This elliptic curve's coefficient `b`, in the Weierstrass elliptic curve equation: `y² = x³ + ax + b`"""

    size_bits: int
    """
    Size of this elliptic curve's sub-group in bits, the bit-length of the order of the sub-group generated by the
    curve's common, public base point (generator).
    """

    curve_aliases: list[str]
    """A list of one or more aliases this elliptic curve is known by, including the primary name given by `curve`."""

    @staticmethod
    def _supported_curve_aliases() -> dict[str, list[str]]:
        """
        Returns a dictionary of supported elliptic curve names, where each key is the primary name for a supported
        curve, and the value is a list of aliases for that curve.
        :return: A dictionary of supported elliptic curve aliases keyed by a curve's primary name.
        """
        return {
            'P-256': ["P-256", "NIST P-256", "secp256r1", "prime256v1", "nistp256", "p256"],
            'P-384': ["P-384", "NIST P-384", "secp384r1", "prime384v1", "nistp384", "p384"],
            'P-521': ["P-521", "NIST P-521", "secp521r1", "prime521v1", "nistp521", "p521"]
        }

    @classmethod
    def for_curve_name(cls, curve_name: str) -> WeierstrassEllipticCurveConfig | None:
        """
        Factory function for constructing a configuration context for a supported elliptic curve, given its common name
        or alias. Returns `None` if the provided curve name is not a supported curve.
        :param curve_name: The primary name or alias of a supported elliptic curve.
        :return: A configuration context for a supported elliptic curve; or `None` if not supported.
        """
        # Check if provided elliptic curve name is a primary name for a supported curve.
        if curve_name in cls._supported_curve_aliases():
            return cls._curve_by_primary_name(curve_name)
        else:  # otherwise check if provided curve name is an alias for a supported curve
            for curve, aliases in cls._supported_curve_aliases().items():
                if curve_name in aliases:
                    return cls._curve_by_primary_name(curve)
            else:  # provided curve name is not a primary name or alias for a supported curve
                return None

    @classmethod
    def _curve_by_primary_name(cls, primary_curve_name: str) -> WeierstrassEllipticCurveConfig | None:
        """
        Returns an elliptic curve configuration context given the curve's primary name, if it is a supported curve;
        otherwise, returns `None`.
        :param primary_curve_name: The primary name of a supported elliptic curve.
        :return: A configuration context for a supported elliptic curve, given its primary name; or `None` if not
                 supported.
        """
        match primary_curve_name:
            case "P-256":
                return cls.p256()
            case _:  # unsupported curve
                return None

    @property
    def curve_size_bytes(self) -> int:
        return math.ceil(self.size_bits / 8)

    @property
    def base_point(self) -> ECC.EccPoint:
        """
        A common, public base point (generator) of the elliptic curve, which generates a cyclic sub-group with order
        ``self.order``.
        """
        return ECC.construct(curve=self.curve, d=1).pointQ

    @property
    def identity(self) -> ECC.EccPoint:
        """
        Returns the point-at-infinity (`O`), which is the elliptic curve group's additive identity.
        """
        return self.base_point.point_at_infinity()

    @staticmethod
    def is_identity(point: ECC.EccPoint) -> bool:
        """
        Returns whether the given elliptic curve point is the point-at-infinity (`O`), the group's additive identity.
        """
        return point.is_point_at_infinity()

    def is_point_on_curve(self, point: ECC.EccPoint) -> bool:
        """
        Returns whether the given elliptic curve point is on this curve, inclusive of the point-at-infinity, by
        verifying the point's x and y coordinates satisfy the Weierstrass elliptic curve equation:
        `y² = x³ + ax + b mod p`, where `p` is the prime modulus of the curve `E(F_p)` over the finite field `F_p` and
        `a` and `b` are the curve's defined coefficients.
        """
        if not point.is_point_at_infinity():
            y_squared: int = pow(point.y, 2, self.modulus)
            x_cubed: int = pow(point.x, 3, self.modulus)

            return y_squared == (x_cubed + self.coeff_a * point.x + self.coeff_b) % self.modulus
        else:
            return True  # the identity element (point-at-infinity) is always considered "on the curve"

    def has_curve_name(self, curve_name: str):
        """
        Returns whether the given name matches a known alias of this Weierstrass elliptic curve configuration context.
        """
        return curve_name in self.curve_aliases

    @classmethod
    def secp256r1(cls) -> WeierstrassEllipticCurveConfig:
        """
        Factory function for constructing a configuration context for the standard NIST P-256 elliptic curve (also
        known as SECP-256r1).
        """
        return WeierstrassEllipticCurveConfig(
            curve="P-256",
            order=0xffffffff_00000000_ffffffff_ffffffff_bce6faad_a7179e84_f3b9cac2_fc632551,
            modulus=0xffffffff_00000001_00000000_00000000_00000000_ffffffff_ffffffff_ffffffff,  # 2^256 - 2^224 + 2^192 + 2^96 - 1
            cofactor=1,
            coeff_a=0xffffffff_00000001_00000000_00000000_00000000_ffffffff_ffffffff_fffffffc,
            coeff_b=0x5ac635d8_aa3a93e7_b3ebbd55_769886bc_651d06b0_cc53b0f6_3bce3c3e_27d2604b,
            size_bits=256,
            curve_aliases=["p256", "NIST P-256", "P-256", "prime256v1", "secp256r1", "nistp256"]
        )

    @classmethod
    def p256(cls) -> WeierstrassEllipticCurveConfig:
        """
        Convenience factory function for constructing a configuration context for the standard NIST P-256 elliptic curve
        (also known as SECP-256r1), named after a common short alias.
        """
        return cls.secp256r1()

    @classmethod
    def secp384r1(cls) -> WeierstrassEllipticCurveConfig:
        """
        Factory function for constructing a configuration context for the standard NIST P-384 elliptic curve (also
        known as SECP-384r1).
        """
        return WeierstrassEllipticCurveConfig(
            curve="P-384",
            order=0xffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_c7634d81_f4372ddf_581a0db2_48b0a77a_ecec196a_ccc52973,
            modulus=0xffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_fffffffe_ffffffff_00000000_00000000_ffffffff,  # 2^384 - 2^128 - 2^96 + 2^32 - 1
            cofactor=1,
            coeff_a=0xffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_fffffffe_ffffffff_00000000_00000000_fffffffc,
            coeff_b=0xb3312fa7_e23ee7e4_988e056b_e3f82d19_181d9c6e_fe814112_0314088f_5013875a_c656398d_8a2ed19d_2a85c8ed_d3ec2aef,
            size_bits=384,
            curve_aliases=["p384", "NIST P-384", "P-384", "prime384v1", "secp384r1", "nistp384"]
        )

    @classmethod
    def p384(cls) -> WeierstrassEllipticCurveConfig:
        """
        Convenience factory function for constructing a configuration context for the standard NIST P-384 elliptic curve
        (also known as SECP-384r1), named after a common short alias.
        """
        return cls.secp384r1()

    @classmethod
    def secp521r1(cls) -> WeierstrassEllipticCurveConfig:
        """
        Factory function for constructing a configuration context for the standard NIST P-521 elliptic curve (also
        known as SECP-521r1).
        """
        return WeierstrassEllipticCurveConfig(
            curve="P-521",
            order=0x01ff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_fffffffa_51868783_bf2f966b_7fcc0148_f709a5d0_3bb5c9b8_899c47ae_bb6fb71e_91386409,
            modulus=0x01ff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff,  # 2^521 - 1
            cofactor=1,
            coeff_a=0x01ff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_ffffffff_fffffffc,
            coeff_b=0x0051_953eb961_8e1c9a1f_929a21a0_b68540ee_a2da725b_99b315f3_b8b48991_8ef109e1_56193951_ec7e937b_1652c0bd_3bb1bf07_3573df88_3d2c34f1_ef451fd4_6b503f00,
            size_bits=521,
            curve_aliases=["p521", "NIST P-521", "P-521", "prime521v1", "secp521r1", "nistp521"]
        )

    @classmethod
    def p521(cls) -> WeierstrassEllipticCurveConfig:
        """
        Convenience factory function for constructing a configuration context for the standard NIST P-521 elliptic curve
        (also known as SECP-521r1), named after a common short alias.
        """
        return cls.secp521r1()

    @classmethod
    def is_curve_supported(cls, curve_name: str) -> bool:
        """
        Returns whether the provided elliptic curve common/primary name or alias is supported.
        """
        # Check if provided elliptic curve name is a primary name for a supported curve.
        return curve_name in cls._supported_curve_aliases() or (
            # Otherwise, check if provided curve name is an alias for a supported curve.
            any(
                curve_name in aliases for aliases in cls._supported_curve_aliases().values()
            )
        )
