###############################################################################
# (c) 2024 W. Spann Systems Consulting
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

"""
Implements an interactive zero-knowledge (ZK) range proof protocol for proving that a committed integer `x` value falls
within a specified range `[0, q)`, for an integer `x` in `[0, l]` where ``l := floor(q/3)``.

This module implements the prover and verifier client components of the ZK range proof protocol (`ZKRangeProofProver`
and `ZKRangeProofVerifier`), as well as the common context that encapsulates pre-shared parameters. The prover and
verifier clients each maintain their own secret local state and protocol session state, which is encapsulated in the
`ZKRangeProofProverSession` and `ZKRangeProofVerifierSession` session classes, respectively.

This session state can be stored in a local database or other persistent storage controlled by the prover or verifier,
respectively, keyed by its unique `session_id` (i.e., unique to the prover or verifier, but not necessarily equal).
Alternatively, if the ZK range proof protocol is being executed by a delegated party on behalf of either party, this
session state can be stored in a database controlled by that delegated party. If building a client application that can
recover from crashes or restarts, the prover or verifier client's session state should be persisted to disk or a
database after each protocol step, along with an encrypted copy of its secret local state.

The prover and verifier clients use their corresponding session object, along with their secret local state,
respectively, to interactively execute the ZK range proof protocol. At the end of a successful protocol execution, for
a prover-committed value `x` in the prescribed range `[0, l]`, the prover will have proven to the verifier that the
committed value `x` falls within the specified range `[0, q)` to be proven.

The interactive protocol implemented here is that of Yehuda Lindell, as described in his paper:
"Fast Secure Two-Party ECDSA Signing" (https://eprint.iacr.org/2019/114.pdf).
"""

from __future__ import annotations

import base64
import uuid

from dataclasses import dataclass
from typing import Union

from uuid import UUID

from scriptless_zkp.commitments.hmac_commitments import (
    KeyedHashCommitment,
    KeyedHashCommitmentUtils,
    RevealedKeyedHashCommitment
)
from scriptless_zkp.he import paillier
from scriptless_zkp.utils import random_integer_in_range, random_integer_of_size, integer_to_bytes

DEFAULT_RANGE_PROOF_SECURITY_PARAM = 40
DEFAULT_PAILLIER_KEY_SIZE = 3072
MIN_PAILLIER_KEY_SIZE = 2048


class ZKRangeProofContext:
    membership_interval_max: int  # upper limit `q` (exclusive) of range committed value will be proven to fall within
    witness_range_max: int        # upper limit `l` (exclusive) of the witness value's actual range (`floor(q/3)`)
    security_param: int           # security parameter `t` (default 40)
    paillier_key_size: int        # Paillier public/private key size (default: 2048 bits)

    def __init__(
            self,
            membership_interval_max: int,
            security_parameter: int = DEFAULT_RANGE_PROOF_SECURITY_PARAM,
            paillier_key_size: int = DEFAULT_PAILLIER_KEY_SIZE
    ):
        self.membership_interval_max = membership_interval_max
        self.witness_range_max = membership_interval_max // 3
        self.security_param = security_parameter

        # Paillier key size must be a multiple of 256 bits (e.g., 2048, 3072, 4096, etc.)
        if paillier_key_size < MIN_PAILLIER_KEY_SIZE:
            raise ValueError(
                f"Insufficient Paillier key-size: {paillier_key_size} -- Minimum is {MIN_PAILLIER_KEY_SIZE} bits."
            )
        elif not ZKRangeProofContext._validate_paillier_key_size(membership_interval_max, paillier_key_size):
            raise ValueError(
                f"Insufficient Paillier key-size: {paillier_key_size} -- Minimum is ceil(log2(2q^2 + q)) bits, where q"
                f" is the elliptic curve sub-group's order (i.e., the size of the group generated by base point G)."
            )

        self.paillier_key_size = paillier_key_size

    @staticmethod
    def _validate_paillier_key_size(membership_interval_max: int, paillier_key_size_bits: int) -> bool:
        """
        Checks if the provided Paillier key size is sufficient for use in Y. Lindell's Zero-Knowledge Range Proof
        (or Y. Lindell's 2-party ECDSA protocol's associated ZK proof for the language L_PDL, which embeds this ZK
        range proof). This method specifically checks whether ``N_min > 2q^2 + q``, where `N_min` is the minimal
        Paillier public modulus of bit-size `|N|` and `q` is the elliptic curve sub-group's order.
        :param membership_interval_max: upper limit `q` (exclusive) of range the witness value will be proven to fall
               within.
        :param paillier_key_size_bits: the size of the Paillier public modulus `N` in bits.
        :return: whether the specified Paillier key size is sufficient for use in Y. Lindell's ZK range proof protocol
                 (or the ZK proof for the language L_PDL in Y. Lindell's 2-party ECDSA protocol).
        """

        # Paillier key-size of 2048 bits is sufficient for elliptic curves with |q| <= 521 bits
        # (i.e., |N_min| > 1043 bits). (Note: Paillier public moduli must be a multiple of 256 bits.)
        if (
            paillier_key_size_bits >= 2048 and membership_interval_max.bit_length() <= 521
            and paillier_key_size_bits % 256 == 0
        ):
            return True
        elif membership_interval_max.bit_length() > 521 and paillier_key_size_bits % 256 == 0:
            # Minimum Paillier modulus N_min for q, per the ZK range proof protocol (of Y. Lindell).
            min_paillier_modulus_for_q = 2 * (membership_interval_max ** 2) + membership_interval_max  # i.e., N > 2q^2 + q
            # Lower bound on random Paillier key's modulus (i.e., `(2^(key_size/2 - 1) + 1)^2` ).
            paillier_modulus_lower_bound: int = (2 ** (paillier_key_size_bits // 2 - 1) + 1) ** 2  # e.g., (2^1023 + 1)^2

            return paillier_modulus_lower_bound > min_paillier_modulus_for_q
        else:
            return False


@dataclass
class ProverRandomChallenges:
    group1: list[int]
    group2: list[int]

    def __init__(self, challenge_group1: list[int], challenge_group2: list[int]):
        self.group1 = challenge_group1
        self.group2 = challenge_group2

    @classmethod
    def generate_random_challenges(cls, context: ZKRangeProofContext) -> ProverRandomChallenges:
        # Challenge Group 1: random integers in the range [l, 2l], where l := floor(q/3), q := membership_proof_max
        group1: list[int] = [random_integer_in_range(context.witness_range_max, 2 * context.witness_range_max + 1)
                             for _ in range(0, context.security_param)]  # t random integers, where t := security_param
        # Challenge Group 2: initially set to `w1_i - l` for each w1_i in Challenge Group 1 (for i in [1, t])
        group2: list[int] = [w1 - context.witness_range_max for w1 in group1]

        # For each i in [1, t], swap w1_i with w2_i with probability 1/2 (indep. for each i).
        group1, group2 = cls._randomly_swap_challenges(context.security_param, group1, group2)

        return cls(group1, group2)

    @property
    def group_size(self) -> int:
        return len(self.group1)

    def encrypt_challenges(self, public_key: paillier.PaillierPublicKey) -> ProverChallengeCiphertexts:
        encrypted_group1: list[paillier.EncryptedUnsignedInteger] = [public_key.encrypt(w1) for w1 in self.group1]
        encrypted_group2: list[paillier.EncryptedUnsignedInteger] = [public_key.encrypt(w2) for w2 in self.group2]

        return ProverChallengeCiphertexts(encrypted_group1, encrypted_group2)

    def challenge_group(self, group_num: int) -> list[int]:
        return self.group1 if group_num == 1 else self.group2

    def challenge_at(self, group_num: int, index: int) -> int:
        return self.group1[index] if group_num == 1 else self.group2[index]

    @staticmethod
    def _randomly_swap_challenges(security_param: int, group1: list[int], group2: list[int]) -> (list[int], list[int]):
        # For each i in [1, t], swap w1_i with w2_i with probability 1/2 (indep. for each i).
        for i in range(1, security_param + 1):  # for each i in [1, t]
            # Produce a fair coin flip (i.e., heads=1 vs. tails=0 w/ probability: 1/2)
            coin_flip: int = random_integer_in_range(0, 2)  # random integer in: [0, 1]
            if coin_flip == 1:  # heads: swap elements at i
                # Swap the values in Challenge Group 1 and Challenge Group 2 at index i.
                group1[i], group2[i] = group2[i], group1[i]
            # else (tails): do nothing (i.e., don't swap elements at i)

        return group1, group2


@dataclass
class ProverChallengeCiphertexts:
    group1: list[paillier.EncryptedUnsignedInteger]
    group2: list[paillier.EncryptedUnsignedInteger]

    def __init__(
            self,
            encrypted_challenge_group1: list[paillier.EncryptedUnsignedInteger],
            encrypted_challenge_group2: list[paillier.EncryptedUnsignedInteger]
    ):
        self.group1 = encrypted_challenge_group1
        self.group2 = encrypted_challenge_group2

    @classmethod
    def from_string_encoding(cls, encoded_ciphertexts: str) -> ProverChallengeCiphertexts:
        pub_key_and_ciphertexts: list[str] = encoded_ciphertexts.split(".")

        if len(pub_key_and_ciphertexts) != 2:
            raise ValueError(
                f"Invalid string encoding for encrypted Prover challenges -- missing Paillier public key "
                f"[encoded_ciphertexts='{encoded_ciphertexts}']"
            )

        public_key_export: str = pub_key_and_ciphertexts[0]
        public_key: paillier.PaillierPublicKey = paillier.PaillierPublicKey.import_public_key(public_key_export)

        ciphertext_groups: list[str] = pub_key_and_ciphertexts[1].split(":")

        if len(ciphertext_groups) != 2:
            raise ValueError(
                f"Invalid string encoding for encrypted Prover challenges -- two groups of ciphertexts expected"
                f" [encoded_ciphertexts='{encoded_ciphertexts}']"
            )

        group1_delimited_base64: str = ciphertext_groups[0]
        group2_delimited_base64: str = ciphertext_groups[1]

        group1: list[paillier.EncryptedUnsignedInteger] = [
            paillier.EncryptedUnsignedInteger.from_base64_encoding(ciphertext, public_key)
            for ciphertext in group1_delimited_base64.split(",")
        ]
        group2: list[paillier.EncryptedUnsignedInteger] = [
            paillier.EncryptedUnsignedInteger.from_base64_encoding(ciphertext, public_key)
            for ciphertext in group2_delimited_base64.split(",")
        ]

        if len(group1) != len(group2):
            raise ValueError(
                f"Invalid string encoding for encrypted Prover challenges -- ciphertext groups are of unequal size"
                f"[encoded_ciphertexts='{encoded_ciphertexts}']"
            )

        if len(group1) < DEFAULT_RANGE_PROOF_SECURITY_PARAM:
            raise ValueError(
                f"Invalid string encoding for encrypted Prover challenges -- insufficient number of ciphertexts"
                f"[encoded_ciphertexts='{encoded_ciphertexts}', min_ciphertexts_per_group="
                f"{DEFAULT_RANGE_PROOF_SECURITY_PARAM}]"
            )

        return cls(group1, group2)

    @property
    def group_size(self) -> int:
        return len(self.group1)

    @property
    def paillier_public_key(self) -> paillier.PaillierPublicKey:
        # All ciphertexts for both groups should have been created using the same Paillier public key, so simply return
        # the public key from group #1's first Paillier ciphertext's `EncryptedUnsignedInteger` wrapper.
        return self.group1[0].public_key

    def __str__(self) -> str:
        return self.encode_as_string()

    def __repr__(self) -> str:
        return (
            f"ProverChallengeCiphertexts(paillier_public_key='{self.paillier_public_key.export_public_key()}', "
            f"group1_base64='{self._string_encode_group(1)}', group2_base64='{self._string_encode_group(2)}')"
        )

    def ciphertext_group(self, group_num: int) -> list[paillier.EncryptedUnsignedInteger]:
        return self.group1 if group_num == 1 else self.group2

    def ciphertext_at(self, group_num: int, index: int) -> paillier.EncryptedUnsignedInteger:
        return self.group1[index] if group_num == 1 else self.group2[index]

    def encode_as_string(self) -> str:
        """
        Encodes the two groups of encrypted Prover challenges, using a base64-based string encoding formatted as
        follows:
            `{pub-key-export}.{group1-export}:{group2-export}`, where `{group1-export}` & `{group2-export}` are each
        comma-delimited lists of base64-encoded Paillier ``EncryptedUnsignedInteger`` values, produced via the latter's
        ``encode_to_base64()`` method, and `{pub-key-export}` is a comma-delimited list of base64-encoded values
        produced via ``PaillierPublicKey``'s ``export_public_key()`` method.
        """
        return ".".join([
            self.paillier_public_key.export_public_key(),
            ":".join([
                self._string_encode_group(1),
                self._string_encode_group(2)
            ])
        ])

    def _string_encode_group(self, group_num: int) -> str:
        group: list[paillier.EncryptedUnsignedInteger]

        match group_num:
            case 1:
                group = self.group1
            case 2:
                group = self.group2
            case _:
                raise ValueError(
                    f"Invalid group number specified for string encoding encrypted Prover challenges: {group_num}"
                )

        return ",".join([
            str(map(
                lambda ciphertext: ciphertext.encode_to_base64(),
                group
            ))
        ])


@dataclass
class WitnessTweakedProverChallenges:
    tweaked_challenges: list[Union[tuple[int, int, int, int], tuple[int, int, int]]]

    def __init__(self, tweaked_challenges: list[Union[tuple[int, int, int, int], tuple[int, int, int]]]):
        self.tweaked_challenges = tweaked_challenges

    @property
    def count(self) -> int:
        return len(self.tweaked_challenges)

    def challenge_at(self, index: int) -> Union[tuple[int, int, int, int], tuple[int, int, int]]:
        return self.tweaked_challenges[index]

    def encode_as_string(self) -> str:
        return ",".join(
            map(
                str, self.tweaked_challenges
            )
        )


@dataclass
class VerifierChallengeRevealResponse:
    verifier_challenge: int
    app_session_id: UUID
    revealed_commitment: RevealedKeyedHashCommitment

    def __init__(
            self,
            verifier_challenge: int,
            app_session_id: UUID,
            revealed_verifier_challenge_commitment: RevealedKeyedHashCommitment
    ):
        self.verifier_challenge = verifier_challenge
        self.app_session_id = app_session_id
        self.revealed_commitment = revealed_verifier_challenge_commitment

    @classmethod
    def from_string_encoding(cls, encoded_response: str) -> VerifierChallengeRevealResponse:
        # Parse the verifier's challenge, app session ID, and the commitment's verification key & hash algorithm from
        # the encoded response string.
        verifier_challenge, app_session_id, verification_key_base64, hash_algo = encoded_response.split(":")
        # Decode the base64-encoded verification key.
        verification_key: bytes = base64.b64decode(verification_key_base64, validate=True)

        return cls(
            int(verifier_challenge),
            UUID(app_session_id),
            RevealedKeyedHashCommitment(
                verifier_challenge,
                bytearray(verification_key),
                hash_algo
            )
        )

    @property
    def commitment_verification_key(self) -> bytearray:
        return self.revealed_commitment.verification_key

    def __str__(self) -> str:
        return self.encode_as_string()

    def __repr__(self) -> str:
        verification_key_base64: str = base64.b64encode(self.commitment_verification_key).decode(encoding='utf-8')

        return (
            f"VerifierChallengeRevealResponse(verifier_challenge={self.verifier_challenge}, "
            f"app_session_id={self.app_session_id!s}, commitment_verification_key={verification_key_base64}, "
            f"commitment_hash_algorithm='{self.revealed_commitment.hash_algorithm}')"
        )

    def encode_as_string(self) -> str:
        return ":".join([
            str(self.verifier_challenge),
            str(self.app_session_id),
            base64.b64encode(self.commitment_verification_key).decode(encoding='utf-8'),
            self.revealed_commitment.hash_algorithm
        ])


class ZKRangeProofProverSession:
    session_id: UUID              # prover unique session ID for this protocol session
    context: ZKRangeProofContext
    protocol_step: int                                                # current protocol step (1-4)
    paillier_pub_key: paillier.PaillierPublicKey
    witness_ciphertext: paillier.EncryptedUnsignedInteger             # encrypted secret witness
    random_challenges: ProverRandomChallenges | None = None           # note: populated in protocol step #2 (prover)
    verifier_challenge_commitment: KeyedHashCommitment | None = None  # note: populated in protocol step #1 (verifier)
    verifier_challenge: int | None = None  # verifier challenge revealed by verifier in protocol step #3 (verifier)
    app_session_id: UUID | None = None     # app session ID revealed by verifier in protocol step #3 (verifier)

    def __init__(
            self,
            context: ZKRangeProofContext,
            paillier_public_key: paillier.PaillierPublicKey,
            committed_secret_ciphertext: paillier.EncryptedUnsignedInteger,
            session_id: UUID = uuid.uuid4()
    ):
        self.session_id = session_id
        self.context = context
        self.paillier_pub_key = paillier_public_key
        self.witness_ciphertext = committed_secret_ciphertext
        self.protocol_step = 1  # prior to prover's first protocol step (#2), verifier commitment received (step #1)


class ZKRangeProofVerifierSession:
    session_id: UUID              # unique session ID for this protocol session (from application layer)
    context: ZKRangeProofContext
    protocol_step: int                                   # current protocol step (1-4)
    prover_paillier_pub_key: paillier.PaillierPublicKey
    prover_committed_secret_ciphertext: paillier.EncryptedUnsignedInteger
    verifier_challenge_commitment: KeyedHashCommitment | None = None
    prover_challenge_ciphertexts: ProverChallengeCiphertexts | None = None
    verifier_challenge: int | None = None  # verifier's challenge `e` in `{0,1}^t`, where `t` is the security parameter

    def __init__(
            self,
            context: ZKRangeProofContext,
            app_session_id: UUID,
            prover_paillier_public_key: paillier.PaillierPublicKey,
            prover_committed_secret_ciphertext: paillier.EncryptedUnsignedInteger
    ):
        self.session_id = app_session_id
        self.context = context
        self.prover_paillier_pub_key = prover_paillier_public_key
        self.prover_committed_secret_ciphertext = prover_committed_secret_ciphertext
        self.protocol_step = 0  # prior to verifier's first protocol step (#1)


class ZKRangeProofProver:
    session: ZKRangeProofProverSession
    paillier_key_pair: paillier.PaillierKeyPair  # one-time use Paillier key-pair for this prover session
    secret_witness: int                          # secret witness `x` being proven to lie in: [0, q/3]

    def __init__(
            self,
            context: ZKRangeProofContext,
            secret_witness: int,
            session_id: UUID = uuid.uuid4()
    ):
        self.paillier_key_pair = paillier.PaillierKeyPair.generate(context.paillier_key_size)
        self.secret_witness = secret_witness

        # Encrypt the secret value `x`
        witness_ciphertext: paillier.EncryptedUnsignedInteger = (
            self.paillier_key_pair.public_key.encrypt(secret_witness)
        )
        self.session = ZKRangeProofProverSession(
            context,
            self.paillier_key_pair.public_key,
            witness_ciphertext,
            session_id
        )

    @property
    def session_id(self) -> UUID:
        return self.session.session_id

    @property
    def context(self) -> ZKRangeProofContext:
        return self.session.context

    def step2_and_prepare_transmission(self, encoded_verifier_commitment: str) -> str:
        """
        Given the Verifier's commitment to their challenge `e` and shared session ID `sid` (received as a string
        encoding), the Prover performs Step #2 of the interactive ZK range proof protocol, generating & encrypting
        random challenge values, and returning a string encoding of the encrypted challenges for transmission to the
        Verifier.
        """
        if self.session.protocol_step < 1:
            raise ValueError("Verifier protocol step #1 (initialization) not yet completed.")
        elif self.session.protocol_step > 2:
            raise ValueError("Prover protocol step #2 already completed.")

        # Parse the verifier's commitment to their challenge `e` and shared session ID `sid`.
        verifier_challenge_commitment = KeyedHashCommitment.from_string_encoding(encoded_verifier_commitment)

        encrypted_prover_challenges: ProverChallengeCiphertexts = self._init_prover_protocol(
            verifier_challenge_commitment
        )

        return encrypted_prover_challenges.encode_as_string()

    def _init_prover_protocol(
            self,
            verifier_challenge_commitment: KeyedHashCommitment
    ) -> ProverChallengeCiphertexts:
        # Protocol Step #2: Prover receives verifier's commitment to its challenge `e` & shared session ID `sid`.
        self.session.verifier_challenge_commitment = verifier_challenge_commitment

        self.session.random_challenges = ProverRandomChallenges.generate_random_challenges(self.context)
        self.session.protocol_step = 2  # completion of prover's first protocol step (#2)

        return self.session.random_challenges.encrypt_challenges(self.session.paillier_pub_key)

    def step4_and_prepare_transmission(self, encoded_revealed_verifier_challenge: str) -> str:
        if self.session.protocol_step < 2:
            raise ValueError("Prover protocol step #2 not yet completed.")
        elif self.session.protocol_step >= 4:
            raise ValueError("Prover protocol step #4 already completed.")

        revealed_verifier_challenge = VerifierChallengeRevealResponse.from_string_encoding(
            encoded_revealed_verifier_challenge
        )

        tweaked_prover_challenges: WitnessTweakedProverChallenges = self._receive_revealed_verifier_challenge(
            revealed_verifier_challenge
        )

        return tweaked_prover_challenges.encode_as_string()

    def _receive_revealed_verifier_challenge(
            self,
            revealed_verifier_challenge: VerifierChallengeRevealResponse
    ) -> WitnessTweakedProverChallenges:
        # Convert verifier's challenge & session ID to byte arrays (in big-endian byte order) & concatenate them.
        committed_secret: bytes = b"".join([
            integer_to_bytes(revealed_verifier_challenge.verifier_challenge),
            revealed_verifier_challenge.app_session_id.bytes
        ])

        revealed_commitment: RevealedKeyedHashCommitment = self.session.verifier_challenge_commitment.reveal(
            committed_secret,
            revealed_verifier_challenge.commitment_verification_key
        )
        # Verify revealed commitment (i.e., `e`, `sid`) matches the verifier's commitment to these values.
        if not revealed_commitment.verify(self.session.verifier_challenge_commitment.commitment):
            raise ValueError("Revealed verifier challenge commitment does not match the verifier's commitment.")

        self.session.verifier_challenge = revealed_verifier_challenge.verifier_challenge
        self.session.app_session_id = revealed_verifier_challenge.app_session_id
        self.session.protocol_step = 4  # indicate completion of protocol step #4

        # return self._answer_verifier_challenge(
        #     self.secret_witness,
        #     revealed_verifier_challenge.verifier_challenge,
        #     self.session.random_challenges,
        #     # self.session.prover_challenge_ciphertexts
        # )

    def _answer_verifier_challenge(self) -> WitnessTweakedProverChallenges:
        t: int = self.context.security_param  # security parameter `t` (default 40)
        # Obtain the binary representation of the verifier's challenge `e` as a string of `t` bits.
        verifier_challenge_binary: str = format(
            self.session.verifier_challenge, f"0{t}b"
        )

        tweaked_challenges: list[Union[tuple[int, int, int, int], tuple[int, int, int]]] = []
        for i in range(0, t):
            if verifier_challenge_binary[i] == "0":
                tweaked_challenges.append((
                    self.session.random_challenges.challenge_at(1, i),
                    # r1_i,  # randomness used in prover challenge ciphertext c1_i
                    self.session.random_challenges.challenge_at(2, i)
                    # r2_i   # randomness used in prover challenge ciphertext c2_i
                ))
            else:  # verifier_challenge_binary[i] == "1"
                z1: int = self.session.random_challenges.challenge_at(1, i) + self.secret_witness
                z2: int = self.session.random_challenges.challenge_at(2, i) + self.secret_witness
                # TODO: Select z = z1 or z2 based on which lies within [l, 2l].
                #   Append (j, z, r * r_j_i mod N), where 'r' is the randomness used in the prover's encrypted witness.


class ZKRangeProofVerifier:
    session: ZKRangeProofVerifierSession
    verifier_challenge: int  # random verifier challenge `e` in [0, 2^t), where `t` is the security parameter
    revealed_verifier_challenge_commitment: RevealedKeyedHashCommitment | None = None

    def __init__(
            self,
            context: ZKRangeProofContext,
            app_session_id: UUID,
            prover_committed_secret_ciphertext: paillier.EncryptedUnsignedInteger,
            prover_paillier_public_key: paillier.PaillierPublicKey,
    ):
        self.session = ZKRangeProofVerifierSession(
            context, app_session_id, prover_paillier_public_key, prover_committed_secret_ciphertext
        )
        self.verifier_challenge = random_integer_of_size(context.security_param)

    @property
    def session_id(self) -> UUID:
        return self.session.session_id

    @property
    def context(self) -> ZKRangeProofContext:
        return self.session.context

    def step1_and_prepare_transmission(self) -> str:
        """
        Initializes the verifier's protocol session (Protocol Step #1), and returns a string-encoded message for
        transmission to the Prover, including a sealed commitment to the verifier's challenge.

        :return: the sealed commitment to the verifier's random challenge, using a base64-based string encoding.
        :raises ValueError: if the Verifier's session object indicates this initialization step (Step #1) has already
                occurred (i.e., `protocol_step > 0`).
        """
        if self.session.protocol_step > 0:
            raise ValueError("Verifier protocol step #1 (initialization) already completed.")

        verifier_challenge_commitment = self._init_verifier_protocol()

        return verifier_challenge_commitment.encode_as_string()

    def _init_verifier_protocol(self) -> KeyedHashCommitment:
        """
        Produces a keyed-hash commitment to (e, sid), and send to prover, where `sid` is the app session ID.
        """
        # Commit to verifier's challenge `e` and shared session ID `sid`.
        verifier_challenge_commitment, revealed_verifier_challenge_commitment = KeyedHashCommitmentUtils().commit(
            # Convert verifier's challenge & session ID to byte arrays (in big-endian byte order) & concatenate them.
            b"".join([
                integer_to_bytes(self.verifier_challenge),  # Verifier's (40-bit) challenge as 5-byte array (big-endian)
                self.session_id.bytes                       # Session ID (UUID) as 16-byte array (big-endian)
            ])
        )
        self.session.verifier_challenge_commitment = verifier_challenge_commitment
        self.revealed_verifier_challenge_commitment = revealed_verifier_challenge_commitment
        self.session.protocol_step = 1  # indicate completion of protocol step #1

        # Return sealed commitment to verifier's challenge `e` and shared session ID `sid`.
        # Protocol Step #1: Verifier sends this sealed commitment to the prover.
        return verifier_challenge_commitment

    def step3_and_prepare_transmission(self, encoded_encrypted_prover_challenges: str) -> str:
        """
        Performs Protocol Step #3 and returns a string-encoded message for transmission to the Prover.

        Verifier receives the prover's encrypted challenges `c1_i` and `c2_i` for each `i` in `[1, t]`, stores these
        ciphertexts in its session object for later use, then "decommits" to the verifier challenge's commitment.

        Finally, it prepares a message to be transmitted to the Prover, including the revealed verifier challenge, app
        session ID, and the commitment's (ephemeral) verification key (enabling the Prover to verify the sealed
        commitment actually commits to the revealed values).

        :param encoded_encrypted_prover_challenges: the prover's encrypted challenges `c1_i` and `c2_i` for each `i` in
               `[1, t]`, provided in a field-delimited base64-based string encoding.
        :return: a string-encoded message for transmission to the Prover, including the verifier's revealed challenge
                 `e`, its revealed shared app session ID `sid`, and the commitment's (ephemeral) verification key.
        :raises ValueError: if the Verifier's session object indicates this receipt of encrypted Prover challenges step
                (Step #3) has already occurred (i.e., `protocol_step >= 3`), or if the initialization step (Step #1)
                has not yet occurred.
        """
        if self.session.protocol_step < 1:
            raise ValueError("Verifier protocol step #1 (initialization) not yet completed.")
        elif self.session.protocol_step >= 3:
            raise ValueError("Verifier protocol step #3 already completed.")

        encrypted_prover_challenges: ProverChallengeCiphertexts = ProverChallengeCiphertexts.from_string_encoding(
            encoded_encrypted_prover_challenges
        )

        verifier_challenge_reveal_response = self._receive_encrypted_prover_challenges(encrypted_prover_challenges)

        return verifier_challenge_reveal_response.encode_as_string()

    def _receive_encrypted_prover_challenges(
            self,
            encrypted_prover_challenges: ProverChallengeCiphertexts
    ) -> VerifierChallengeRevealResponse:
        """
        Verifier receives the prover's encrypted challenges `c1_i` and `c2_i` for each i in [1, t].

        :param encrypted_prover_challenges: the prover's encrypted challenges `c1_i` and `c2_i` for each i in [1, t].
        :return: the verifier's challenge `e`, the shared session ID `sid`, and the revealed commitment to `e` and
                `sid`.
        """
        # Protocol Step #3: Verifier receives prover's encrypted challenges `c1_i` and `c2_i` for each i in [1, t].
        self.session.prover_challenge_ciphertexts = encrypted_prover_challenges
        self.session.protocol_step = 3  # indicate completion of protocol step #3

        # Protocol Step #3: Verifier sends their challenge `e`, shared app session ID `sid`, and the commitment's
        # verification key to the prover.
        return VerifierChallengeRevealResponse(
            self.verifier_challenge,
            self.session_id,
            self.revealed_verifier_challenge_commitment
        )
